### ISSUE TITLE
AsyncSemaphore deadlock: EnterAsync holds lock while blocking on cancellation handler which needs lock

### ISSUE THREAD

**Issue by jasonmalinowski** [microsoft/vs-threading#1000]
(This is being reported from the analysis from devdiv-1496681

#### Bug description
AsyncSemaphore.EnterAsync has this specific line:

https://github.com/microsoft/vs-threading/blob/683b45cfb44f5c1b5f8069f6efee40a633a17141/src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs#L144

Which calls:

https://github.com/microsoft/vs-threading/blob/683b45cfb44f5c1b5f8069f6efee40a633a17141/src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs#L356

If you get particularly unlucky with your timing, that call to cancellationTokenRegistration.Dispose() will block on the cancellation handler completing; if that's running on another thread and potentially blocked in it's own right, then the monitor is held and all other calls to AsyncSemaphore will block, synchronously.

I admit it's not immediately obvious to me if this will deadlock permanently: https://github.com/microsoft/vs-threading/blob/683b45cfb44f5c1b5f8069f6efee40a633a17141/src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs#L222 might be trying to acquire the monitor as well in the cancellation handler -- we might have a case where the cancellation handler is acquiring the monitor and the monitor is blocking on the cancellation handler. But my analysis might be incorrect there.

I suspect one fix is to move info.Cleanup() outside the monitor lock, but not sure if other fixes are available too.

#### Repro steps
Have code using AsyncSemaphore with cancellation, and get unlucky.

**Comment by AArnott** [comment]
More notes from @jasonmalinowski's investigation:

404 threads are blocked trying to acquire the monitor in AsyncSemaphore.EnterAsync.
The one thread that _does_ have the monitor is in here:

```
>	mscorlib.dll!System.Threading.SpinWait.SpinOnce() Line 146	C#
 	mscorlib.dll!System.Threading.CancellationTokenSource.WaitForCallbackToComplete(System.Threading.CancellationCallbackInfo callbackInfo) Line 946	C#
 	mscorlib.dll!System.Threading.CancellationTokenRegistration.Dispose() Line 90	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.AsyncSemaphore.WaiterInfo.Cleanup() Line 357	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.AsyncSemaphore.EnterAsync(System.TimeSpan timeout, System.Threading.CancellationToken cancellationToken) Line 147	C#
```

22 threads are here in StreamJsonRpc:
```
 	mscorlib.dll!System.Threading.SpinWait.SpinOnce() Line 146	C#
 	mscorlib.dll!System.Threading.CancellationTokenSource.WaitForCallbackToComplete(System.Threading.CancellationCallbackInfo callbackInfo) Line 946	C#
 	mscorlib.dll!System.Threading.CancellationTokenRegistration.Dispose() Line 90	C#
 	mscorlib.dll!System.Threading.CancellationTokenSource.Dispose(bool disposing) Line 582	C#
>	StreamJsonRpc.dll!StreamJsonRpc.JsonRpc.InvokeCoreAsync(StreamJsonRpc.Protocol.JsonRpcRequest request, System.Type expectedResultType, System.Threading.CancellationToken cancellationToken) Line 1906	C#
```

22 other threads (suspicious the same number?) are here:

```
>	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.AsyncSemaphore.CancellationHandler(object ste) Line 234	C#
```
