### ISSUE TITLE
New analyzer: using Task<T> instead of resource T

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#102]
### Example

```csharp
AsyncSemaphore lck;
using (lck.EnterAsync())
{
    // ...
}
```

### Expected warning:

> Using statement resource is a Task&lt;T&gt;, where T is disposable

### Expected code fix (when enclosing method is `async`):

```csharp
AsyncSemaphore lck;
using (await lck.EnterAsync())
{
    // ...
}
```

**Comment by AArnott** [comment]
I wonder if this analyzer would be better to go into the AsyncUsageAnalyzers library though, given it isn't related to this threading library. Thoughts, @sharwell ?

**Comment by sharwell** [comment]
That would be fine. I only reported it here because it affected a usage scenario when working with this library, combined with the fact that this library uses analyzers to encourage correct usage. :smile:
