### ISSUE TITLE
AsyncReaderWriterLock released when out of scope

### ISSUE THREAD

**Issue by blair-ahlquist** [microsoft/vs-threading#1024]
#### Bug description
A reference to the Releaser cannot be kept to be disposed at a later time. When the method that obtains the lock is exited, the lock is released.
 
#### Repro steps
```
        [Test] //NUnit
        public async Task LockHeldIndirectionTestAsync()
        {
            AsyncReaderWriterLock arwl = new AsyncReaderWriterLock();

            async Task<IDisposable> enterAsync() => await arwl.ReadLockAsync();

            using (await enterAsync())
            {
                Assert.IsTrue(arwl.IsReadLockHeld); // Fails as arwl.IsReadLockHeld returns false
            }
        }
```

#### Expected behavior
Lock will be held until Releaser is explicitly disposed.

#### Actual behavior
Lock was disposed as soon as the method in which the lock was obtained was exited. If `enterAsync()` is replaced with a direct call `arwl.ReadLockAsync()` then the test passes.

- Version used: 17.1.46
- Application (if applicable):

**Comment by blair-ahlquist** [comment]
It is not just the readonly properties. This test also fails:

```
        [Test]
        public async Task UpgradeableReadLockTestAsync()
        {
            AsyncReaderWriterLock rwl = new AsyncReaderWriterLock();

            async Task<IDisposable> enterUpgradeableReadLockAsync() => await rwl.UpgradeableReadLockAsync();
            
            using (await enterUpgradeableReadLockAsync())
            {
                CancellationTokenSource cts = new CancellationTokenSource();
                cts.CancelAfter(TimeSpan.FromSeconds(5));

                using (await rwl.WriteLockAsync(cts.Token))
                {

                }
            }
        }
```

**Comment by AArnott** [comment]
You're misreading the problem. You certainly can box up the releaser to release later. But you're testing with `IsReadLockHeld` from a different context to the one you entered the lock with. That property tells you whether *you* hold the read lock. But you don't hold it. The async method you called and exited holds it (and still holds it, as the releaser hasn't been disposed of). 
You can test this yourself by trying to obtain a write lock where you are testing for a read lock. You'll find you can't get it. But if you then dispose of the releaser (even after you boxed it), your write request will get through.

**Comment by blair-ahlquist** [comment]
@AArnott Thanks for your reply. What exactly do you mean by "context"? I assume `SynchronizationContext`. I realized after your comment that I was in an environment that did not have an SC - so I should not have expected my first example to work. Yet, I tried the same example in a WindowsForms environment - which does have an SC - logged a ThreadID of 1 everywhere, and still did not end up with `IsReadLockHeld == true` when the lock entry was wrapped in another method. So it doesn't seem that having an SC is enough. But no matter, this is not code I should expect to use...

But here is what does matter: my second example. Can you spend some time evaluating this case? I would like to use `upgradeableReadLockAsync`, but I reached a deadlock in that code. I don't know how I can accomplish that in my code if I must obtain all locks within the same method. What seems to be missing here is an object returned from `upgradeableReadLockAsync` which itself has a method to upgrade to write.

My apologies if I'm still misreading the issue.

**Comment by AArnott** [comment]
No, it's not SynchronizationContext. It's ExecutionContext. `AsyncLocal<T>` tracks its value through the `ExecutionContext`. It's how even across threads or across yielding awaits, we can track "who" entered the lock. When your `enterUpgradeableReadLockAsync` method entered the lock as an async method, _it_ holds the lock and not its caller.

Why do you need a helper method to acquire the lock for you? Generally you should acquire the lock, use it, and exit it. You can use it in other methods you call, but you can't call another method to enter the lock and then use the lock after that method returns.

Strictly speaking, if you remove the `async` modifier from your helper method, you'll find it works. But that doesn't leave you with a very interesting helper method.

**Comment by blair-ahlquist** [comment]
@AArnott Thank you so much for the info. I haven't heard of `ExecutionContext` before and I was wondering what kind of magic was going on behind the scenes.

> Why do you need a helper method to acquire the lock for you?

We have a lock node class that enables us to lock subtrees of our data - hence the wrapping. Currently we are using `ReaderWriterLockSlim` as the core lock class, but need to async-ify our code and vs-threading looked like a good bet - especially as it has the upgradeable read functionality.

It sounds like vs-threading might still be the way to go since no other library we found has that feature. Although I still think that `upgradeableReadLockAsync` should return an object that allows upgrade-to-write (under the principle of "if you hold the object returned by the lock request, then you hold the lock"), it sounds like that would be a major refactor.

Thanks for your time!

**Comment by AArnott** [comment]
> it sounds like that would be a major refactor.

Ya, sorry. We had to have a lock mechanism that would propagate and be detectable automatically, so possession of an object didn't cut it.
