### ISSUE TITLE
Cannot run tests locally

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#103]
When I try to run the tests locally (via Visual Studio 2017 Test Explorer), I get the following message:

> Message: System.IO.FileLoadException : Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=15.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

I tried editing the Microsoft.VisualStudio.Threading.csproj project file to disable signing temporarily (with `<SignAssembly>False</SignAssembly>`, but that just changed the error message to the following:

> Message: System.IO.FileLoadException : Could not load file or assembly 'Microsoft.VisualStudio.Validation, Version=15.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

**Comment by AArnott** [comment]
Launch VS from a cmd window where you have SET signtype=mock, then rebuild. 

We'll doc this is the Readme or contributing doc.

**Comment by AArnott** [comment]
Also you have to register for skip verification with the workaround I mentioned. This is documented for another repo of ours here: https://github.com/Microsoft/vs-streamjsonrpc/blob/master/CONTRIBUTING.md#running-tests
