### ISSUE TITLE
Error thrown for application after installing latest package to coreapp3.1 project

### ISSUE THREAD

**Issue by cortex-ab** [microsoft/vs-threading#1033]
#### Bug description
We have a web application that we have just installed the latest version of Microsoft.VisualStudio.Threading onto (```17.2.32```).
After deploying it to our test environments, an error was thrown:
```The framework 'Microsoft.WindowsDesktop.App', version '3.1.0' was not found.```
It seems there is now a requirement on that where there wasn't before.

#### Repro steps
I created an empty project, csproj:
``` xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

</Project>
```
after building it, the runtimeconfig.json file produced looks like this:
``` json
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "3.1.0"
    },
    "configProperties": {
      "System.GC.Server": true,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false
    }
  }
}
```

After installing the package:
csproj:
``` xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Threading" Version="17.2.32" />
  </ItemGroup>

</Project>
```
runtimeconfig.json:
``` json
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "frameworks": [
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "3.1.0"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "3.1.0"
      }
    ],
    "configProperties": {
      "System.GC.Server": true,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false
    }
  }
}
```

I'm assuming this was not indended? previous version 17.1.46 does not have the same issue.

I was trying to see what had that dependency and found that 
``` json 
          "PresentationCore": "4.0.0.0",
          "PresentationFramework.Aero": "4.0.0.0",
          "PresentationFramework.Aero2": "4.0.0.0",
          "PresentationFramework.AeroLite": "4.0.0.0",
          "PresentationFramework.Classic": "4.0.0.0",
          "PresentationFramework": "4.0.0.0",
          "PresentationFramework.Luna": "4.0.0.0",
          "PresentationFramework.Royale": "4.0.0.0",
          "PresentationUI": "4.0.0.0",
          "ReachFramework": "4.0.0.0",
```
was pulled in...but not sure what has referenced them either.

For now I have downgraded the package back to 17.1.46 and everything is working

**Comment by AArnott** [comment]
This is in fact by design, because for netcoreapp3.1 we added the `DispatcherSynchronizationContext`-related APIs that previously were only found on net472. 
You can avoid the WindowsDesktop runtime requirement by targeting net5.0+, which added the ability for us to split `net5.0` from `net5.0-windows` targeting so that `net5.0` consumers could avoid the WindowsDesktop runtime requirement.
