### ISSUE TITLE
VSTHRD003 fails to fire on non-awaited Task created outside JTF.Run delegate

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-threading#108]
This report from John Hart:

```csharp
public static T WaitAndGetResult<T>(this Task<T> task, CancellationToken cancellationToken)
{
   return ThreadHelper.JoinableTaskFactory.Run(() => task.WithCancellation(cancellationToken));
}
```

**Comment by sharwell** [comment]
❓ Which is the problem?

1. VSSDK003 is not yet implemented
2. VSSDK003 does not work when `task` is an argument (e.g. `JTF.Run(() => task)` also does not report)
2. VSSDK003 works for `JTF.Run(() => task)` but not for `JTF.Run(() => task.WithCancellation(ct))`

**Comment by AArnott** [comment]
@sharwell: no. 2
The analyzer only reported a diagnostic when `task` was *awaited*.
