### ISSUE TITLE
VSTHRD103 mis-fires when async version is not accessible (ie., not public)

### ISSUE THREAD

**Issue by TahirAhmadov** [microsoft/vs-threading#1082]
#### Bug description
When calling an available (eg. public) sync method, and the target object has a method which is not available (eg. protected) and is "async" (returns task-like, has same signature, and ends with "Async"), it suggests to use it.

#### Repro steps
```cs
class Foo
{
  string? _text;
  public void Bind(string text) => this._text = text;
  protected async Task BindAsync(string text) { this.Bind(text); await this.HandleBoundAsync(); }
  protected async Task HandleBoundAsync() { ... }
}
var foo = new Foo();
foo.Bind("abc"); // VSTHRD103
```

#### Expected behavior
Should not fire

#### Actual behavior
Fired

- Version used: 17.2.32
- Application (if applicable):

**Comment by AArnott** [comment]
I couldn't repro this on the tip of `main` or on the `v17.2.32` tag where the bug was reported, with the following test:

```cs
[Fact]
public async Task DoNotSuggestInaccessibleAsyncAlternative()
{
    string test = @"
    using System.Threading.Tasks;
    class Foo
    {
      string? _text;
      public void Bind() {}
      protected Task BindAsync() => Task.CompletedTask;
    }
    class Bar
    {
      public async Task DoSomethingAsync(Foo foo)
      {
        foo.Bind(); // VSTHRD103
      }
    }
    ";

    await Verify.VerifyAnalyzerAsync(test);
}
```

If I switch `protected` to `public` the diagnostic is created as expected, so it appears this already works.

We can reactivate if we can get a verifiable repro.

**Comment by TahirAhmadov** [comment]
Strange, now it doesn't work at all: (both lines where it says `// VSTHRD103` don't get the suggestion)

![image](https://github.com/microsoft/vs-threading/assets/16783987/f8b72198-c7d4-4b14-a1b0-dd2b7293c497)

**Comment by AArnott** [comment]
Which version are you using when you see that?

**Comment by TahirAhmadov** [comment]
Same version as before, 17.2.32.

**Comment by AArnott** [comment]
Can you try the latest released version?

**Comment by TahirAhmadov** [comment]
Same result:

![image](https://github.com/microsoft/vs-threading/assets/16783987/33a1c7b3-bcdd-47b8-b153-7c6303161f9f)

**Comment by AArnott** [comment]
Thanks. I'll look into it.

**Comment by TahirAhmadov** [comment]
To further assist in resolving this:

![image](https://github.com/microsoft/vs-threading/assets/16783987/bfdf566e-b2e9-4cea-b7fd-f6863b085861)

[VSTHRD103Test.zip](https://github.com/microsoft/vs-threading/files/13217872/VSTHRD103Test.zip)

**Comment by AArnott** [comment]
LOL. Your `Main` method returns `void`. VSTHRD103 only encourages calling of async alternatives when the invocation is done within an async method (or a method that returns Task). If I switch your `Main` method to return `Task`, `BindPublic` gets flagged.

**Comment by TahirAhmadov** [comment]
Hahaha yes how did I not notice that before. Anyway, I'm now also unable to reproduce my original issue, neither using that older version nor using the latest version. Really strange. Thank you for your time.
