### ISSUE TITLE
VSTHRD200 should not fire for methods starting with "When"

### ISSUE THREAD

**Issue by drewnoakes** [microsoft/vs-threading#1222]
#### Bug description

VSTHRD200 reports async methods not having an "Async" suffix to their names.

There is precedent for async methods to start with `When`, such as `Task.WhenAny`.

#### Repro steps

```c#
Task WhenCompleted() => _tcs.Task;
```

#### Expected behavior

No diagnostic.

#### Actual behavior

Diagnostic!

- Version used: `17.7.15-preview`
- Application: [dotnet/project-system](https://github.com/dotnet/project-system/blob/5d84c70b3cd4c6da60ee3c2ff686cf3edf25e258/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/GlobalSuppressions.cs#L74-L76)

**Comment by sharwell** [comment]
`Task.WhenAny` is a static transformation method (transforms one or more tasks into an aggregating task). The examples provided from dotnet/project-system do not share this characteristic, and in my opinion provide direct evidence for which this exception should not be made. The methods like [`WhenInitialized`](https://github.com/dotnet/project-system/blob/0953875295673b8d873ec941134100fe3f29111c/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/IWorkspaceWriter.cs#L54) should have instead been named `WhenInitializedAsync`.

**Comment by drewnoakes** [comment]
I don't see that distinction as relevant personally. `WhenInitialized` is still transforming one or more tasks into an aggregating task, it's just that the caller isn't passing them in.

**Comment by AArnott** [comment]
I share @sharwell's concern that the precedent for this isn't very strong, and your example:
```cs
Task WhenCompleted() => _tcs.Task;
```

...actually demonstrates an anti-pattern as it's returning a 'foreign task' as defined by VSTHRD003.

If you can find a bunch of examples across libraries, or a best practices book or well-respected doc that encourages the pattern you're espousing, we can reconsider.

For pre-existing APIs that you cannot rename, you should use `#pragma warning disable VSTHRD200` around those specific declarations. For future APIs, I believe it would be best to follow the convention.
