### ISSUE TITLE
VSTHRD004 is misreported on call sites that update the awaitable returned from SwitchToMainThreadAsync

### ISSUE THREAD

**Issue by tmat** [microsoft/vs-threading#1267]
#### Bug description

VSTHRD004 is reported for call sites:

```C#
await _threadingContext.JoinableTaskFactory.SwitchToMainThreadAsync(cancellationToken).NoThrowAwaitable();
```

#### Repro steps
Roslyn has multiple cases for the above code.

#### Expected behavior
No warning reported.

#### Actual behavior
Warning reported.

- Version used:  17.8.14
- Application (if applicable): Roslyn

**Comment by sharwell** [comment]
Duplicate of #1232
