### ISSUE TITLE
VSTHRD200 should not fire for API Methods

### ISSUE THREAD

**Issue by richardtallent-erm** [microsoft/vs-threading#1268]
#### Bug description
Public async methods with an HTTP method attribute in `Microsoft.AspNetCore.Mvc` (*e.g.*, `[HttpPost]`) on a class decorated with the `[ApiController]` attribute should not be *required* to have a name ending in `Async`.

#### Repro steps

```C#
using Microsoft.AspNetCore.Mvc;

[ApiController]
public class MyController : ControllerBase {
  // VSTHRD200 should not warn for this method, even though it is async.
  [HttpPost]
  public async Task<IActionResult> Initialize() {
  }
}
```

#### Expected behavior
For these methods, VSTHRD200 should not warn.

#### Actual behavior
VSTHRD200 warns for these methods.

- Version used: 17.8.14, .NET 8
- Application (if applicable): VS Code

#### Additional context

VSTHRD200 enforces a naming convention suffix of `Async` to remind a developer *using C# to call the method* to use `await` for that call. 

However, the intent of these methods is to define an API be called by a web browser over HTTP. An application's API endpoints should be named based on their function, not their implementation, since the browser/consumer does not and should not care about the application's use of threading.

At least, this should be configurable. Otherwise, the only options are to disable VSTHRD200 completely (and it *is* usually useful) or to litter one's API code with `#pragma` statements to disable it for each API endpoint method.

**Comment by AArnott** [comment]
Thanks for the feedback. I agree what you describe merits a different policy. Just brainstorming here though, you have a few options that sound better than "to disable VSTHRD200 completely (and it is usually useful) or to litter one's API code with #pragma statements to disable it for each API endpoint method":

1. Have one `#pragma warning disable VSTHRD200` line at the top of each controller file.
2. Have one `.editorconfig` file in the directory containing all your controllers that disables VSTHRD200. This leaves it enabled for the rest of your project.

What this _doesn't_ address is any non-API async methods you declare in those same controller files (e.g. async private methods). 
We try to avoid taking on a task of adding recognition of various frameworks into analyzers, as that could be committing to an unknown large size of work as various frameworks come to us with "support us too!" requests. So I'm curious of what you think to my two workarounds above.

**Comment by richardtallent-erm** [comment]
Thanks for the feedback!

1. As you mentioned, I still often have supporting methods within the controllers that are async and should follow the normal convention, so a file-wide directive wouldn't be ideal, and splitting into partial classes *just* to avoid this warning would also be suboptimal.

2. My controllers aren't all in the same folder, they are separated by module/feature (it's a fairly large app).

I can understand not to bake in a bunch of "IF ASP.NET-specific attribute THEN..." logic.

I suppose `[SuppressMessage]` might be the most reasonable option... at least it's cleaner than `#pragma`.

**Comment by AArnott** [comment]
I don't suppose ASP.NET Core offers a setting to trim `Async` off action names so you can follow the convention for those methods, does it?

**Comment by EklipZgit** [comment]
I give this issue resolution a 0/10. The package specifically says "intended for use outside of visual studio extensions too", where by far the largest use case for C# is AspNetCore. And yet I have to hack my codebase not to throw silly warnings about controller actions not being named async? Program.Main as well? 
> In C# 7.1 you will be able to do a proper async Main. The appropriate signatures for Main method has been extended to:

public static Task Main();
public static Task<int> Main();
public static Task Main(string[] args);
public static Task<int> Main(string[] args);

🙃
