### ISSUE TITLE
Call JoinableTaskFactory(new JoinableTaskContext()).RunAsync() in InitializeComponent caused designer error

### ISSUE THREAD

**Issue by ctechid** [microsoft/vs-threading#1282]
#### Bug description
Call JoinableTaskFactory(new JoinableTaskContext()).RunAsync() in InitializeComponent caused designer error

#### Repro steps
Call **JoinableTaskFactory(new JoinableTaskContext()).RunAsync()** in **InitializeComponent** caused designer error

        private void InitializeComponent()
        {
             ...
             TestButton.Click += (sender, e) => _ = new JoinableTaskFactory(new JoinableTaskContext()).RunAsync(() =>  TestButton_ClickAsync(sender, e));
             ...
        }

#### Expected behavior
The designer does not error when the event is used in **InitializeComponent()**.

#### Actual behavior
The designer error when the event was called inside InitializeComponent(). 
- Version used: **Microsoft.VisualStudio.Threading 17.8.14** 
- Application (if applicable): 

#### Additional context
![image](https://github.com/microsoft/vs-threading/assets/117961207/ffb51596-3a68-4537-9869-10bb258f500a)

**SOLUTION**
**Move the event outside **InitializeComponent()** no error appears in the designer**.

**Comment by AArnott** [comment]
`JoinableTaskContext` is supposed to be a singleton in a process. You shouldn't be creating one in an event handler just to call `RunAsync`. 

It looks like you're going to all the trouble just to invoke an async method from an event handler. But what are you gaining for your trouble? Why not just do this:

```cs
 TestButton.Click += (sender, e) => _ = TestButton_ClickAsync(sender, e);
```

**Comment by ctechid** [comment]
> `JoinableTaskContext` is supposed to be a singleton in a process. You shouldn't be creating one in an event handler just to call `RunAsync`.
> 
> It looks like you're going to all the trouble just to invoke an async method from an event handler. But what are you gaining for your trouble? Why not just do this:
> 
> ```cs
>  TestButton.Click += (sender, e) => _ = TestButton_ClickAsync(sender, e);
> ```

Thank You, What you said also works well.
I used the previous one because it was recommended when a warning appeared in the error list window of VS2022
