### ISSUE TITLE
Is the Analyzer library included implicity in the dotnet or should be downloaded separatedly?

### ISSUE THREAD

**Issue by HakamFostok** [microsoft/vs-threading#1297]
Is the `Microsoft.VisualStudio.Threading.Analyzers` included implicity when we are using .NET or should those Analyzers nuget downloaded separately?

If I understood the documentation correctly, I see that the Analyzers are not included implicity in .NET Projects, shouldn't including the Analyzers be the default, if this is the case, should this be requested here, or in the .NET Repo?

**Comment by AArnott** [comment]
The analyzers in this repo are _not_ in the .NET SDK. A PackageReference is required to get them.

The plan from the .NET team is to 'copy' the analyzers that they like from this repo into the SDK and change the diagnostic codes while doing so. This has been gradually happening over the last few years. Some analyzers are specific to threading patterns that require the threading library itself (also in this repo), so those analyzers will not migrate to the SDK.
