### ISSUE TITLE
Struggling to enforce "always need await"

### ISSUE THREAD

**Issue by chrismcv** [microsoft/vs-threading#1300]
#### Is your feature request related to a problem? Please describe.
I'm trying to add refactor protection when making an sync method async.

An example that I'm struggling with at the moment

```
class Customer { public int Id {get;set;}}

Customer GetCustomer(object data) {...}
Customer CreateCustomer(object data) {...}

var customer = args.PatientId != null ? GetCustomer(data) : CreateCustomer(data);

DoSomethingWithCustomerId(customer.Id);
```

Recently after a refactor, both methods (`GetCustomer`, `CreateCustomer`) became async, and the implicit type of `var customer` changed from `Customer` to `Task<Customer>`.

#### Describe the solution you'd like
Ideally, I'd like to be able to enforce that all async methods are awaited regardless of call context.

#### Describe alternatives you've considered

I've tried the following analysers with no success:

``` 
dotnet_diagnostic.CS4014.severity = error

dotnet_diagnostic.LindhartAnalyserMissingAwaitWarning.severity = error
dotnet_diagnostic.CSE005.severity = none
dotnet_diagnostic.CSE007.severity = none
dotnet_diagnostic.CSE008.severity = error
dotnet_diagnostic.CSE009.severity = error

dotnet_diagnostic.VSTHRD110.severity = error
dotnet_diagnostic.VSTHRD107.severity = error
dotnet_diagnostic.VSTHRD100.severity = error
dotnet_diagnostic.VSTHRD110.severity = error
dotnet_diagnostic.AsyncFixer03.severity = error
dotnet_diagnostic.AsyncFixer04.severity = error
```

**Comment by AArnott** [comment]
It sounds like you're looking for better refactoring, or otherwise a C# language service or compiler feature. I don't think there's anything this repo can do.
