### ISSUE TITLE
Slow performance when we have loop JTF dependencies

### ISSUE THREAD

**Issue by lifengl** [microsoft/vs-threading#132]
When we create JTF friendly semaphore in this style, and have many calls into this code, we saw huge CPU usage inside JTF.Disjoin method.

            return JoinableFactory.RunAsync(async delegate
            {
                using (JoinableCollection.Join())
                using (await _gate.DisposableWaitAsync().ConfigureAwait(false))
                {
                    await task().ConfigureAwait(false);
                }
            });

This produces a joinable task collection, in which each joinable task joins to the collection itself.  When we have a large amount of calls into this code (226 calls in the dump file), we will build up lots of loop dependencies in the joinable task structure, (basically, we have n tasks depends on all n tasks.)  JTF code doesn’t handle loop dependencies efficiently. (We didn’t think about this pattern when code was written.)  In this case, the time to remove one task is O(n^3).

**Comment by lifengl** [comment]
need investigate how to improve the inner data structure, or at least, we should not use this pattern in the code. (Create the out JTF with a different JTF factory/collection).

**Comment by AArnott** [comment]
It seems the problem might be that everyone joins and adds themselves to the collection for the duration of their interest in the lock.
Might we reduce the problem by:
1. When waiting in the queue, *join* the collection.
1. When the semaphore is received, disjoin the collection and add self as member to the collection.

This way, membership in the collection is limited to just about 1 element. And no one ever joins and is a member at the same time.

**Comment by jviau** [comment]
In your proposal, are you in a `RunAsyn` while awaiting the semaphore? I think that is a large contribution to this issue. However, due to the way semaphores work, to remove the `RunAsync` while awaiting the semaphore, you use must `ConfigureAwait(false)` (or the new inline extension method). This poses a problem when you have a contract that promises execution on the thread it was started on. I put up a PR that attempts to solve both of these problems here https://github.com/Microsoft/vs-threading/pull/313

**Comment by AArnott** [comment]
> In your proposal, are you in a RunAsyn while awaiting the semaphore?

No. So the "join" is only effective if the caller happened to have created a JoinableTask themselves. And if they didn't, they'll never block the UI thread waiting for the semaphore and thus there's no reason to join anyway.

And yes, after writing this comment I started reviewing your PR and see that's effectively what you're doing. :)

**Comment by AArnott** [comment]
We now have `ReentrantSemaphore` that avoids the problematic pattern.
@lifengl we can revisit if this is still a problem.
