### ISSUE TITLE
Ignore EF add async methods

### ISSUE THREAD

**Issue by grosch-intl** [microsoft/vs-threading#1343]
#### Bug description
VSTHRD103 is telling me to use `AddRangeAsync`, yet it shouldn't.  The EF Core methods explicitly say to neither call `AddAsync` nor `AddRangeAsync`

#### Repro steps
await using var context = await factory.CreateContextAsync();
context.AddRange(activeChecklist, inactive);

- Version used: 17.10.48
- Application (if applicable): Visual Studio 2022 Enterprise

**Comment by AArnott** [comment]
Duplicate of #584
