### ISSUE TITLE
Unable to disable some slow analyzers using .editorconfig

### ISSUE THREAD

**Issue by michalciolek** [microsoft/vs-threading#1351]
#### Bug description
I would like to disable some VSTHRD analyzers due to slow execution time. I cannot disable it using `.editorconfig` file.

#### Repro steps
1) Add `dotnet_diagnostic.VSTHRD010.severity = none` to `.editorconfig` file
2) Run msbuild with ReportAnalyzers `msbuild.exe /v:d /p:reportanalyzer=true X.csproj`
3) Find `  9,745   18      Microsoft.VisualStudio.Threading.Analyzers.VSTHRD010MainThreadUsageAnalyzer (VSTHRD010)` in output log

#### Expected behavior
Disabled analyzers should have execution time <0,001

#### Actual behavior
Disabled analyzer `(VSTHRD010)` have 9,745s duration time

- Version used: 17.11.20
- Application (if applicable): winforms .net 8

**Comment by AArnott** [comment]
That sounds like a bug or feature request for dotnet/roslyn. There's nothing we can do to honor a disable request that the compiler isn't better suited to honor.

**Comment by michalciolek** [comment]
It seems to me that the issue is related to the analyzers. Disabling other analyzers works as expected (disabling decrease time to <0,001), eg:

nuget analyzers:
StyleCop.Analyzers SA1121
Roslynator.Analyzers RCS1036

also for embedded analyzers eg. CA2213

**Comment by AArnott** [comment]
Well, I don't know why it would work for some and not others. But we have no plans to fix it as disabling an analyzer is outside the scope of any analyzer AFAIK. 
Either a roslyn bug, or some kind of misconfiguration within your repo are my best guesses.

@sharwell, do you have any other ideas?

**Comment by sharwell** [comment]
As a compilation-end analyzer that also uses `GeneratedCodeAnalysisFlags.Analyze`, analysis cannot be skipped when setting severity to none in **.editorconfig**. It might work to set the severity to none in **.globalconfig**.

**Comment by AArnott** [comment]
Oh! That's very interesting and something we may want to call out in a doc somewhere then.
@michalciolek Can you try these suggestions and share which ones work for you?

**Comment by michalciolek** [comment]
@sharwell You are right. If I disabled analyzers in the global analyzer config file they are actually not executed! I did not know this config file. It was enough to read [this article carefully](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files).

Thank you!
