### ISSUE TITLE
Include System.ValueTuple as an analyzer assembly

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#137]
If you are interested in using tuple types in the analyzer package, you can include **System.ValueTuple.dll** as an analyzer assembly in the same folder where your other analyzer assemblies are. This will allow it to be loaded by Roslyn 1.x.

**Comment by AArnott** [comment]
Yes, I'm aware of that. But it's unnecessary as I found the workaround was simpler than trying to shimmy the extra assembly into the analyzers folder of the nupkg.
