### ISSUE TITLE
New analyser: warn about (delegate).BeginInvoke

### ISSUE THREAD

**Issue by IntelOrca** [Microsoft/vs-threading#146]
I came across the following code when converting our code base to use new threading standards.
```cs
void Main()
{
    var action = DoWork;
    action.BeginInvoke(null, null);
}

void DoWork()
{
    ...
}
```

I am not sure what the best thing to suggest is, but my fix was to make `DoWork` async and switch to a background thread within that. Then call it from a synchronous method using one of the `Forget` extension methods.

**Comment by AArnott** [comment]
The change you describe is fine. But I'm not sure what the analyzer would warn about. I can't think of anything fundamentally wrong with the code you had before, aside from the fact that it's an old pattern that you don't often see anymore.
I guess a negative aspect would be that at least in your sample you never call EndInvoke, so you're not realizing any failure if `DoWork` were to throw. Is that what you were suggesting the analyzer point out?

**Comment by IntelOrca** [comment]
I wasn't sure whether it was considered a bad practice or not as I am not completely sure on how the thread switching works for BeginInvoke. Where do exceptions propagate to if one is thrown in a BeginInvoke?

**Comment by AArnott** [comment]
`BeginInvoke` executes the method on the Threadpool. Exceptions are re-thrown so you can handle them when you call `EndInvoke`.
