### ISSUE TITLE
Lock contention in AsyncReaderWriterLock.TryIssueLock

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#166]
Opening Roslyn.sln in Visual Studio 2017 (15.3 Preview 6).

I observed 11 seconds of lock contention in [`AsyncReaderWriterLock.TryIssueLock`](https://github.com/Microsoft/vs-threading/blob/b7e23fe6d8009f83dfc88b6850d03c7cd7595936/src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock.cs#L921) as a contributor to thread pool starvation. This is an asynchronous type being used in asynchronous code; this lock should be removed to aid to the long-term avoidance of thread pool starvation.

**Comment by AArnott** [comment]
Can you add an ETL trace, or otherwise summarize what the code that holds the lock for an undue amount of time is doing? We do need a lock here, but perhaps we're holding the lock too long either here or somewhere else, leading to the lock contention.

**Comment by AArnott** [comment]
Closing due to not enough data.

**Comment by sharwell** [comment]
@AArnott maybe set up a brainstorming/strategy meeting sometime in the next month? We can review a few of the observations I've seen on different occasions and see if there are any in particular we should spend time investigating.

**Comment by AArnott** [comment]
Done
