### ISSUE TITLE
Code fix for VSTHRD103 tries to await void

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#167]
```csharp
abstract void LogInformation(string data);
abstract void LogInformationAsync(string data);

async Task Method()
{
  LogInformation(data); // apply code fix here
}
```

Expected result:

```
LogInformationAsync(data);
```

Actual result:

```
await LogInformationAsync(data);
```

**Comment by AArnott** [comment]
Thanks for the report. I actually would change the "Expected result" you specified to be "no diagnostic at all" in this case. If you have two methods that both return void but one has an Async suffix, I don't even know what that means, so I am not confident enough to report a diagnostic suggesting you're calling the wrong method.

**Comment by sharwell** [comment]
@AArnott If something gets disabled in this scenario, I lean towards not changing the diagnostic part, but instead just making the code fix a NOP.

**Comment by AArnott** [comment]
Or we could suppress the code fix being offered rather than a no-op. But if we offer the code fix, why no-op rather than switching to the async method but without adding *await* to it?

Why would you prefer to keep the diagnostic in this case rather than remove it altogether?

**Comment by sharwell** [comment]
> Or we could suppress the code fix being offered

Yes, that's what I meant.

> Why would you prefer to keep the diagnostic in this case rather than remove it altogether?

It's reasonable to this the user meant to provide an async feature, event though it got botched.

**Comment by AArnott** [comment]
> It's reasonable to this the user meant to provide an async feature, event though it got botched.

Are you talking about the attempt to be async was botched (by virtue of returning void)?
If so, I'd agree with you. But in that case, I can't predict whether the Async variety will be a fire-and-forget implementation or something else. My best guess would be a fire-and-forget impl, and that would *not* be equivalent to awaiting on the async option or calling the sync option as it was before. So I think if any diagnostic is reported in such a situation, it would perhaps be on the presence of Foo and FooAsync methods where both return void since that seems like a bad pattern.

Thoughts?

**Comment by sharwell** [comment]
> Thoughts?

Not really. In tracking down cases where code should be making async calls but isn't, the larger problem is cases where a synchronous method sits between the caller and callee.

```csharp
void Method();
void MethodAsync(CancellationToken);

void Intermediate() { Method(); }

async Task Entry(CancellationToken cancellationToken)
{
  Intermediate(); // This ends up calling Method instead of MethodAsync
}
```

**Comment by AArnott** [comment]
Yes, that's a very common problem. The analyzers VSTHRD102 thru VSTHRD104 are intended to help avoid patterns like this example, but I think even with them all enabled, your example *might* still get by without a diagnostic being reported. Would you like to file a separate issue for that?

**Comment by sharwell** [comment]
Right now I don't have enough experience with this set of analyzers to have a clear picture of what's missing.
