### ISSUE TITLE
Add .NET Standard 2.0 build to nuget package

### ISSUE THREAD

**Issue by 0x084E** [Microsoft/vs-threading#198]
Since .NET Standard 2.0 is now supported please add it to the nuget package as well.

**Comment by AArnott** [comment]
Already done in 2a2b165c69016d70371c211791adc3de4d92f8ca. 😄

**Comment by AArnott** [comment]
I'm pushing a 15.6-beta update to nuget.org so you can get at the new netstandard2.0 library. It will show up soon.

**Comment by 0x084E** [comment]
Sorry, my fault. I assumed this change was part of the 15.5 update.
Thanks for the beta release!

**Comment by AArnott** [comment]
For my own education, would you mind telling me the value you see in the netstandard2.0 build?

**Comment by 0x084E** [comment]
I'm using this library extensively for various threads (message loops and custom loops). Therefore I build a little wrapper which handles some things for automatically and uses the JoinableTaskContext constructor overload with Thread and SynchrobizationContext parameters for net46 builds. For netstandard2.0 builds I currently use reflection to create it with the thread id.

So there's no real value except cleaner code. And while writing this and thinking about it I realized I don't even rely on this overload. 😕
