### ISSUE TITLE
VSTHRD010 claims Microsoft.VisualStudio.Shell.Interop.IAsyncServiceProvider is not free-threaded

### ISSUE THREAD

**Issue by dgriffen** [Microsoft/vs-threading#216]
Microsoft.VisualStudio.Shell.Interop.IAsyncServiceProvider should be exempt from VSTHRD010 since the implementations are thread safe.

**Comment by AArnott** [comment]
#215 will make this possible

**Comment by AArnott** [comment]
@dgriffen was this object _always_ free-threaded, or did it become free-threaded in a specific VS version?

**Comment by dgriffen** [comment]
It's always been free-threaded as far as I am aware.
