### ISSUE TITLE
VSTHRD002 should not fire in continuations

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#217]
The following code reports VSTHRD002, but it should not:

```csharp
Task<int> task = default;
task.ContinueWith(t => t.Result); // t is known to be completed at the point of t.Result
```

**Comment by AArnott** [comment]
There are other cases, like:
```csharp
await task;
if (task.Result) ...
```

or 
```csharp
if (task.IsCompleted) {
   var r = task.Result;
}
```

In general, until Roslyn has flow analysis APIs available to analyzers I don't think we can cover them all. But `ContinueWith` looks like it's something we can check for pretty easily.
