### ISSUE TITLE
Hide AdditionalFiles from Analyzers in SolutionExplorer

### ISSUE THREAD

**Issue by 0x084E** [Microsoft/vs-threading#223]
Since these files are only for internal usage of the analyzers it would be nice if they wouldn't show up in the root of the project. For me the following works fine:

```
<AdditionalFiles Include="$(MSBuildThisFileDirectory)AdditionalFiles\**" Visible="false" />
```

**Comment by AArnott** [comment]
Thanks for reporting this. Can you tell me which version of the analyzers you have installed, and into which kind of project?
I'm surprised the files show up because I thought items brought in via MSBuild imports were invisible by default.

**Comment by 0x084E** [comment]
I'm using the latest version 15.6.44. These files didn't show up before (I skipped 15.6.31 and used 15.6.11-beta before). The project is a new .NET Core csproj format. This shows also files from imports, at least for some file types (including txt).
