### ISSUE TITLE
Allow single-method exclusions for main thread affinity

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#230]
Some types which are generally restricted to the main thread have methods which can be called from other threads.

Examples:

* `Control.Invoke`
* `Control.BeginInvoke`
* `Control.InvokeRequired`

Currently exclusions to the main thread requirement only apply to types, so these members can't be conditionally excluded.

:memo: It should be possible to exclude properties either by the property name or the name of the implementing method. This is helpful in situations where the getter can be called from any thread but the setter cannot.

**Comment by AArnott** [comment]
The `ShellSettingsManager` class has two constructors, one of which is free-threaded and the other is not. After the ctor is invoked, the rest of the class is free-threaded.
