### ISSUE TITLE
AsyncReaderWriterLock need allow a customized TaskScheduler

### ISSUE THREAD

**Issue by lifengl** [Microsoft/vs-threading#257]
Today, when it issues a lock later, it always uses the default task scheduler and run it in the thread pool.  Allowing a customized scheduler will make it possible for its consumer to control how to schedule the work.

**Comment by AArnott** [comment]
I'm very curious why this is useful. When we use `TaskScheduler.Default`, we specifically *don't* want the continuation executed on the UI thread. Allowing the user to specify the `TaskScheduler` would allow them to violate that. Also, any other policy than the threadpool might take longer to execute and at this point the lock has been granted so we don't want to be slow in getting the lock holder to execute.
