### ISSUE TITLE
VSTHRD010 bulk fix doesn't work

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-threading#277]
In a document with multiple methods that violate VSTHRD010, when trying to apply a bulk fix to the entire document, only one fix is offered.

- Version used: v15.8.72-beta
- Application (if applicable): Dev15.7

**Comment by sharwell** [comment]
Given #275, we could change the analysis to not be a Compilation End analyzer and maybe fix this and some other usability issues at the same time.

**Comment by AArnott** [comment]
It has to be a compilation end analyzer for the transitive analysis, even if it is only one level deep.

**Comment by AArnott** [comment]
@mavasani @heejaechang Any ideas? I'm seeing this for the [VSSDK006 analyzer I just introduced](https://github.com/Microsoft/VSSDK-Analyzers/pull/68) as well.

**Comment by heejaechang** [comment]
are you sure you are giving same equivalent key?

http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeActions/CodeAction.cs,48

fix with same equivalent key is considered  for fix all

**Comment by heejaechang** [comment]
once you have diagnostic and fix offered, FSA shouldn't affect whether you can do "fix all or not"

**Comment by AArnott** [comment]
Fascinating, @heejaechang. I thought the equivalence key was supposed to be unique for each diagnostic that a code fix is offered for. So I've gone to lengths to ensure they're deterministic for a given diagnostic but unique across them. Is there good documentation to describe what equivalence keys are for and how exactly they should be derived?

**Comment by AArnott** [comment]
I guess that xml remarks section is pretty good docs, but it's not discoverable, since Roslyn doesn't include that information in the data tip.

**Comment by heejaechang** [comment]
@mavasani should have written about it somewhere.

**Comment by mavasani** [comment]
https://github.com/dotnet/roslyn/blob/master/docs/analyzers/FixAllProvider.md#selecting-an-equivalence-key-for-code-actions

We do include this link in the stub fixer code generated by Analyzer + Code fix template.

**Comment by AArnott** [comment]
Thanks. I don't use the template since I already have a project full of analyzers and a pattern that I copy and paste for each new one. Back in the day, I'm not sure these templates were around or we didn't know about them. 
This write-up looks great though. Thank you, @mavasani and @heejaechang

**Comment by AArnott** [comment]
See, now here's my problem: the C# warning seems to be misleading. It is exactly why I started making unique equivalencekey's:

>  warning RS1010: Provide an explicit argument for optional parameter 'equivalenceKey', which is non-null and unique across all code actions created by this fixer.

When a code fix provider only offers a single kind of fix, an equivalence key is unnecessary from what I've just learned. But the warning suggests that I need to be sure I produce a key that is unique across all code actions created by this fixer (which tells me, my fixer should never produce the same key twice!). I think the warning wording can be improved. Should I file a bug (assuming you agree, @heejaechang and @mavasani)? Both the warning, and the fact that it's complaining at all really... since again, what benefit does a non-null value add when a fixer only proffers one code action?

**Comment by mavasani** [comment]
`code actions created by this fixer.`

I actually meant unique to each class of code actions registered by a fixer. Sure we can improve the wording to add clarity.

**Comment by mavasani** [comment]
@AArnott Sorry, the poor wording led you down the wrong path. Can you file an issue on roslyn-analyzers to correct it (or send a PR)? Thanks again.

**Comment by sharwell** [comment]
My understanding is the (diagnostic ID, equivalence key) pair defines the "bucket" for all operations that should be applied as a unit for Fix All.
