### ISSUE TITLE
Analyzer assemblies must have a new version with each release

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#279]
#### Bug description

Currently the analyzers assembly is using a versioning policy where the AssemblyVersion is set to major.minor.0.0. This versioning policy makes it impossible for the build to ensure the correct version of this assembly is used in builds involving mixed version references. Every release of an analyzer assembly must increment the version relative to all previous versions to ensure this does not occur.

:memo: This only applies to *analyzer* assemblies, and not to the main library.

**Comment by AArnott** [comment]
This has bitten me several times lately as well, and I have to restart VS to get the new analyzers running after an update. We can fix this.

**Comment by AArnott** [comment]
Note this wasn't entirely fixed in #281. A follow up fix was required: a1527795d66
