### ISSUE TITLE
AsyncLazy depends on the thread pool unnecessary

### ISSUE THREAD

**Issue by lifengl** [Microsoft/vs-threading#290]
AsyncLazy use ConfigureAwait(false) in its wrap of the valueFunction.  This sometime leads into an unnecessary extra thread switching.  That issue defeat the benefit of priority read lock thread in the case where AsyncLazy is being used.
 
                                return await originalValueFactory().ConfigureAwait(continueOnCapturedContext: false);

**Comment by AArnott** [comment]
Without this, the value factory may or may not include a UI thread dependency at the end based on whether the first person to pull on that value was on the UI thread.

We have the `JoinableTask.AwaitShouldCaptureSyncContext` static property that we use in some places of the library to get the `bool` to pass to `ConfigureAwait` that tries to get the best of both worlds: it uses `false`, except when it can tell it is in the context of a `JoinableTask`, in which case it returns `true`. I'm not sure if that's an ideal fit here, but it's an idea.

**Comment by lifengl** [comment]
Yes, we do want the ending logic of the AsyncLazy to be inline with the valueFactory function.  I am preparing a potential fix.
