### ISSUE TITLE
VSTHRD003 should be reported for ConfigureAwait(true)

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#325]
#### Bug description

[VSTHRD003](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD003.md) is only reported for cases where `ConfigureAwait` is not used. Presumably, this is because `ConfigureAwait(false)` is safe in these cases. However, `ConfigureAwait(true)` should be handled in the same manner as a task that does not use `ConfigureAwait` at all.

<details><summary>Remaining data will be completed on request</summary>

#### Repro steps

Code to reproduce the behavior.

#### Actual behavior
What happened instead of what you expected.

- Version used: 
- Application (if applicable): 

#### Additional context

</details>

**Comment by AArnott** [comment]
`ConfigureAwait(false)` is *not* safe, since the Task itself could require the UI thread to complete.

This is just an oversight. Thanks for reporting.

**Comment by sharwell** [comment]
> ConfigureAwait(false) is not safe, since the Task itself could require the UI thread to complete.

Do you have an example for this? It seems that it wouldn't be a problem because the caller would yield.

**Comment by sharwell** [comment]
Oh nevermind. The failure wouldn't occur at the point of the `await`, but the warning is issued because it's the only place where the problematic situation can be readily identified through static analysis.
