### ISSUE TITLE
Treat 'Synchronously' as a suffix for synchronous methods

### ISSUE THREAD

**Issue by sharwell** [microsoft/vs-threading#331]
#### Is your feature request related to a problem? Please describe.

Roslyn uses the following method pairs in some cases:

```csharp
T SomeMethodSynchronously();
Task<T> SomeMethodAsync();
```

#### Describe the solution you'd like

It would be nice if the existing analysis for usage of asynchronous methods considered the naming convention above as a pair, similar to the current treatment of `SomeMethod`/`SomeMethodAsync` as a pair.

#### Describe alternatives you've considered

Renaming the methods in Roslyn, but the convention doesn't appear unreasonable or burdensome on the analyzer implementation.

**Comment by AArnott** [comment]
I'm a bit hesitant to accommodate a single repo's non-standard naming pattern. 
Can we think of a data-driven way to make this work, perhaps?

**Comment by AArnott** [comment]
@sharwell I updated your problem statement to use the `ly` suffix, to be consistent with your issue title and PR.

**Comment by AArnott** [comment]
Are there a *lot* of these methods in the Roslyn public API? Or are these private methods that Roslyn can simply rename?

We might define an attribute that Roslyn could decorate methods with to identify the async alternative.

**Comment by AArnott** [comment]
Ping? @sharwell I'm tempted to close this issue. An answer to my last question may better inform that decision.

**Comment by sharwell** [comment]
We can use a diagnostic suppressor for this, the same way that we use one to suppress VSTHRD200 (Async suffix) on test method names.

**Comment by AArnott** [comment]
That's fine by me. But if diagnostic suppressor's only *suppress*, it doesn't sound like it will deliver what you wanted. I thought you *wanted* a diagnostic when `SomeSynchronous` was called in an async method where `SomeAsync` was also available.

**Comment by sharwell** [comment]
😆 Oh, right! I'm not sure the Roslyn pattern is common enough to generalize here.
