### ISSUE TITLE
Ensure assignment to a discard produces VSTHRD110

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#345]
#### Is your feature request related to a problem? Please describe.

The following code should produce a warning. Currently Roslyn is using discards in a few places to address CS4014 prior to updating the code to enforce VSTHRD110 (a more strict analyzer with the same intent). We should ensure that VSTHRD110 is reported for this scenario.

```csharp
async Task Method()
{
  _ = Task.Run(() => 3); // VSTHRD110: Observe result of async calls
}

**Comment by jjramon1699-ai** [comment]
[A)VENTURE CAPITAL PRIMER-1 1.pdf](https://github.com/user-attachments/files/18680654/A.VENTURE.CAPITAL.PRIMER-1.1.pdf)
[BulkActions.txt](https://github.com/user-attachments/files/18680647/BulkActions.txt)
[DefaultViewIndexerLog.txt](https://github.com/user-attachments/files/18680648/DefaultViewIndexerLog.txt)
[Enterprise_Services_SCSD(ENG)(Jan2024).pdf](https://github.com/user-attachments/files/18680651/Enterprise_Services_SCSD.ENG.Jan2024.pdf)
[FilterFolders.txt](https://github.com/user-attachments/files/18680656/FilterFolders.txt)
[InboxRules.txt](https://github.com/user-attachments/files/18680655/InboxRules.txt)
[LegacySettings.txt](https://github.com/user-attachments/files/18680650/LegacySettings.txt)
[Microsoft-Responsible-AI-Standard-General-Requirements.pdf](https://github.com/user-attachments/files/18680653/Microsoft-Responsible-AI-Standard-General-Requirements.pdf)
[ScheduledFolderLog.txt](https://github.com/user-attachments/files/18680659/ScheduledFolderLog.txt)
[SweepRules.txt](https://github.com/user-attachments/files/18680657/SweepRules.txt)
[SweepRulesLog.txt](https://github.com/user-attachments/files/18680652/SweepRulesLog.txt)
[UserOptions.txt](https://github.com/user-attachments/files/18680658/UserOptions.txt)
[ViewStateConfiguration.txt](https://github.com/user-attachments/files/18680649/ViewStateConfiguration.txt)
