### ISSUE TITLE
Mismatch in line format documentation

### ISSUE THREAD

**Issue by mthalman-msft** [Microsoft/vs-threading#353]
#### Bug description
The [Analyzer Configuration](../blob/master/doc/analyzers/configuration.md) documentation contains mismatches between the line format provided and the sample.  For example, in the "Methods that assert the main thread" section, it defines the line format as `[Namespace.TypeName]::MethodName` but the sample is `Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread` (i.e. no square brackets or double colons).

From my testing, I've found that things only work if you use the format given by the sample; adding the square brackets and double colons makes the setting unrecognized.

Interestingly, in the last section, "Legacy thread switching members", the line format does match the sample.

**Comment by AArnott** [comment]
Thanks for your report. I've updated the samples in the docs to match the spec given above them. If you find the sample worked and the `[]` syntax didn't, my guess is you're using an older version of the analyzers. In that case, I recommend you upgrade.
