### ISSUE TITLE
Passing CancellationToken to ReentrantSemaphore could execute callback on wrong thread?

### ISSUE THREAD

**Issue by davkean** [Microsoft/vs-threading#367]
First of all, thanks @AArnott and recent changes @jviau made, ReentrantSemaphore is exactly what we need for http://github.com/dotnet/project-system.

#### Bug description
Through code inspection, it appears that passing a CancellationToken to ExecuteAsync that is cancelled before it switches back the UI thread, could result in the callback being executed on a thread pool thread instead of the UI thread where it started:

https://github.com/Microsoft/vs-threading/blame/v15.8/src/Microsoft.VisualStudio.Threading/ReentrantSemaphore.cs#L417

This is because the token passed to SwitchToMainThreadAsync has the following meaning:

> A token whose cancellation will immediately schedule the continuation on a threadpool thread.

It looks like this code might be expecting that this operation throws `OperationCanceledException`, I think you want to follow up with `token.ThrowIfCancellationRequested` after the SwitchToMainThreadAsync.

**Comment by sharwell** [comment]
> It looks like this code might be expecting that this operation throws `OperationCanceledException`, I think you want to follow up with `token.ThrowIfCancellationRequested` after the `SwitchToMainThreadAsync`.

The exception is thrown by `MainThreadAwaiter.GetResult()` during the completion of the `await` operation:

https://github.com/Microsoft/vs-threading/blob/87e58106bcd8ad50d2d6eb44a4b8f5b98dbddd23/src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs#L802

**Comment by AArnott** [comment]
> ReentrantSemaphore is exactly what we need

Awesome! I'm glad you've discovered the class then.

> could result in the callback being executed on a thread pool thread instead of the UI thread where it started

What I think you're missing from the doc you reference is that `SwitchToMainThreadAsync` *throws* `OperationCanceledException` back at the continuation. So in fact `ReentrantSemaphore` doesn't execute the delegate at all when the token is canceled, but instead the `Task` returned from `ExecuteAsync` will fault with `OperationCanceledException`, leading the caller to resume (on the context of their choosing based on `ConfigureAwait`)  and experience that exception.

**Comment by davkean** [comment]
Ah, I walked through the code and got as far as this: http://index/?leftProject=Microsoft.VisualStudio.Threading&leftSymbol=hyuxmvwxl8sv&file=JoinableTaskFactory.cs&line=708. I missed that other code. Thanks for updating the docs!
