### ISSUE TITLE
AsyncDebugTools.dll not available in releases

### ISSUE THREAD

**Issue by davkean** [Microsoft/vs-threading#376]
https://github.com/Microsoft/vs-threading/blob/master/doc/dumpasync.md states that AsyncDebugTools.dll is available from [releases](https://github.com/Microsoft/vs-threading/releases). I could only see zip releases of the repository however. I could only find cpsdbg.dll internally - which I'm guessing is an earlier version?

**Comment by AArnott** [comment]
I'm not sure how to automate inclusion of this in every release. But I've uploaded it to [this recent release](https://github.com/Microsoft/vs-threading/releases/tag/v15.8.168) so you can get it from there.

There are a few versions floating around. I'm not sure which version the cpsdbg.dll one is that you found internally -- it could be much older than this one. Or it might be the newer C# implementation that we'll eventually switch the public one to after it's been vetted a bit more.
