### ISSUE TITLE
Close gap between vs-threading analyzers and AsyncUsageAnalyzers

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-threading#382]
AsyncUsageAnalyzers, which the vs-threading analyzers package currently depends on for downstream users, contains some redundancy with what we contain ourselves. In addition, this project is making progress more rapidly than the AsyncUsageAnalyzers. Let's fill in what we're missing and break the dependency.

AsyncUsageAnalyzers | vs-threading analyzers | Notes
--|--|--
[AvoidAsyncSuffix](https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers/blob/master/documentation/AvoidAsyncSuffix.md) | [VSTHRD200](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD200.md) | +support for `ValueTask`
[AvoidAsyncVoid](https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers/blob/master/documentation/AvoidAsyncVoid.md) | [VSTHRD100](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD100.md)
[UseAsyncSuffix](https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers/blob/master/documentation/UseAsyncSuffix.md) | [VSTHRD200](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD200.md) | +support for `ValueTask`
[UseConfigureAwait](https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers/blob/master/documentation/UseConfigureAwait.md) | [VSTHRD111](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD111.md) | +support for `ValueTask`

**Comment by AArnott** [comment]
CC: @sharwell

**Comment by sharwell** [comment]
Here are a few more changes that should be reviewed (they were added to AsyncUsageAnalyzers after the most recent public preview):

* https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers/pull/39
* https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers/pull/40
* https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers/pull/65

**Comment by AArnott** [comment]
AsyncUsageAnalyzers | Feature | Status
--|--|--
DotNetAnalyzers/AsyncUsageAnalyzers#39  | Skip overrides and interface implementations | [already done](https://github.com/Microsoft/vs-threading/blob/490d2ecd0d01a174ea35c45c352eaf985bd1aa8c/src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD200UseAsyncNamingConventionAnalyzer.cs#L78-L81)
DotNetAnalyzers/AsyncUsageAnalyzers#40 | Include CancellationToken parameter | Not done
DotNetAnalyzers/AsyncUsageAnalyzers#65 | Offer both `ConfigureAwait(true && false)` code fixes | [already done](https://github.com/Microsoft/vs-threading/blob/490d2ecd0d01a174ea35c45c352eaf985bd1aa8c/src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD111UseConfigureAwaitCodeFix.cs#L53-L54)

**Comment by AArnott** [comment]
Regarding the CancellationToken parameter one, that's an interesting one. I wonder how much usage it gets. I don't know what % of async methods I write legitimately take no token since they'd have nothing to do with one, but I imagine it's a significant number.

I've wondered about having an analyzer with a similar goal: ensure that it propagates. Assuming I accept one, I should propagate it wherever possible. What has held me back is the analyzer cannot know where [the point of no return](https://blogs.msdn.microsoft.com/andrewarnottms/2014/03/19/recommended-patterns-for-cancellationtoken/) is, and it may end up encouraging folks to ignore that principle, or littering the codebase with pragmas to ignore the warning.

**Comment by AArnott** [comment]
Tracking the last CancellationToken analyzer proposal with #394
