### ISSUE TITLE
AsyncLazyInitializer is not an asynchronous LazyInitializer

### ISSUE THREAD

**Issue by sharwell** [microsoft/vs-threading#413]
#### Bug description

The name `AsyncLazyInitializer` can cause confusion for users w.r.t. `LazyInitializer`. The former is not intended to be an asynchronous form of the latter, and addresses a totally different problem. It should be renamed.

**Comment by AArnott** [comment]
What would you suggest the name be? It's an `AsyncLazy<T>`-based initializer. So the name is a derivation from `AsyncLazy` rather than `LazyInitializer`.

**Comment by AArnott** [comment]
We already shipped this.
