### ISSUE TITLE
VSTHRD102 analyzer has disallowed dependency on Roslyn Workspaces assembly

### ISSUE THREAD

**Issue by jonathanantoine** [Microsoft/vs-threading#423]
#### Bug description
Cannot use the nuget package on MAC on a .net standard project.

#### Repro steps
Build this project :
[ClassLibraryReproAnalyzer.zip](https://github.com/Microsoft/vs-threading/files/2615654/ClassLibraryReproAnalyzer.zip)

#### Expected behavior
Warning because of wrong usage of async keyword.

#### Actual behavior
Warning about a "non loadable assembly" :
`/Users/jonathanantoine.../CSC: Warning AD0001: Analyzer 'Microsoft.VisualStudio.Threading.Analyzers.VSTHRD102AvoidJtfRunInNonPublicMembersAnalyzer' threw an exception of type 'System.BadImageFormatException' with message 'Could not resolve field token 0x040000d4, due to: Could not load type of field 'Microsoft.VisualStudio.Threading.Analyzers.Utils+<>c:<>9__22_0' (5) due to: Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. assembly:/Users/jonathanantoine/.nuget/packages/microsoft.visualstudio.threading.analyzers/15.8.168/analyzers/cs/Microsoft.VisualStudio.Threading.Analyzers.dll type:<>c member:(null)'. (AD0001) (eded.Core.Middle.ApiClient)`

- Version used: 15.8.168
- Application (if applicable): 

#### Additional context
Thanks for your help !

**Comment by AArnott** [comment]
Analyzers aren't supposed to carry a dependency on the Microsoft.CodeAnalysis.Workspaces assembly. That's the bug. It has nothing to do with targeting .netstandard2.0.

**Comment by AArnott** [comment]
We've had this bug in the vssdk-analyzers too: https://github.com/Microsoft/VSSDK-Analyzers/issues/24
I think we should adopt the same fix as we did there: https://github.com/Microsoft/VSSDK-Analyzers/pull/40

**Comment by jonathanantoine** [comment]
Thanks for your analysis!
