### ISSUE TITLE
Check that VSTHRD200 works with C# 8 async enumerable

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-threading#431]
The names of methods that return `IAsyncEnumerable<T>` should have an `Async` suffix.

These methods may include an `async` modifier, and may include a `yield return` or a `yield break`. In fact these traits will be very likely unless the method is just a pass-through to another method. But that would be an implementation detail, and the method should have the suffix regardless.

**Comment by yhvicey** [comment]
Any update?

**Comment by yhvicey** [comment]
Hi @AArnott, will this change be released in recent releases?

**Comment by AArnott** [comment]
Yes. It's available on nuget.org in the latest pre-release.

**Comment by yhvicey** [comment]
Cool! Thanks for your info.
