### ISSUE TITLE
Analyzer proposal: VSTHRD201 Follow-up SwitchToMainThreadAsync(CancellationToken) with ct.ThrowIfCancellationRequested

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-threading#435]
#### Is your feature request related to a problem? Please describe.

Some consumers of `JoinableTaskFactory.SwitchToMainThreadAsync(CancellationToken)` want or expect awaiting the method to throw if the token is canceled, without regard to whether they are on or can obtain the main thread. 

#### Describe the solution you'd like

An analyzer that offers a diagnostic and automated code fix whenever `SwitchToMainThreadAsync(CancellationToken)` is invoked but not immediately followed by a call to `CancellationToken.ThrowIfCancellationRequested()`

This analyzer would be off-by-default, but would allow code bases that desire it to turn it on to set the policy.

#### Describe alternatives you've considered

See #434 for alternatives including a new API, or manually auditing to avoid bugs in special cases like that the token is always canceled on the main thread, and switches to the main thread with that token should never complete successfully when canceled.

**Comment by AArnott** [comment]
CC: @sharwell @CyrusNajmabadi @jasonmalinowski

**Comment by CyrusNajmabadi** [comment]
Sounds good to me.
