### ISSUE TITLE
Can't compile by .Net Native

### ISSUE THREAD

**Issue by yinyue200** [microsoft/vs-threading#446]
#### Bug description
Can't compile by .Net Native

#### Repro steps
Build the repo in RELEASE Mode https://github.com/yinyue200/vsthreadingwithnetnative

#### Expected behavior
build success

#### Actual behavior
1>  Processing application code
1>  Computing application closure and generating interop code
1>    Loading 91 modules...
1>    Generating code...
1>    Interop code generated.
1>  Compiling interop code
1>  Generating System.Reflection.DispatchProxy proxy code.
1>  Cleaning up unreferenced code
1>  Generating native code
1>C:\Users\username\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : ILT0005: 'C:\Users\username\.nuget\packages\runtime.win10-x86.microsoft.net.native.compiler\2.1.8\tools\x86\ilc\Tools\nutc_driver.exe @"C:\Users\username\Source\Repos\App1\App1\obj\x86\Release\ilc\intermediate\MDIL\App1.rsp"' returned exit code -2147483645

- Version used: 15.8.209
- Application (if applicable):

**Comment by AArnott** [comment]
I don't have any experience with .NET Native. I can't make sense of the error code. Can you file an issue against the .NET Native compiler, and loop us in if you know what change (if any) we need to make?

**Comment by yinyue200** [comment]
@AArnott  I think there is a way to workaround the bug through make UWP target the netstandard 1.3 version

**Comment by yinyue200** [comment]
the latest version already fix the issue. Thanks

**Comment by AArnott** [comment]
Ah yes, thanks for closing this, @yinyue200. I suspect this and #557 ended up being duplicates.
