### ISSUE TITLE
Analyzer for VSTHRD010 is not honoring ThrowIfNotOnUIThread in operator overload method

### ISSUE THREAD

**Issue by mthalman-msft** [Microsoft/vs-threading#450]
#### Bug description
Code contained in an operator overload method may attempt to access an object member that requires the main thread.  This will cause a VSTHRD010 rule warning.  But if the code is modified to call ThreadHelper.ThrowIfNotOnUIThread, the warning does not go away.  I only see this behavior on operator overload methods.

#### Repro steps
This isn't my real code but effectively demonstrates the problem:
```
public static bool operator ==(EnvDTE.Project item1, EnvDTE.Project item2)
{
    ThreadHelper.ThrowIfNotOnUIThread();
    return item1.Equals(item2);  // Still produces a VSTHRD010 warning
}
```

#### Expected behavior
There should be no warning.

#### Actual behavior
A warning is produced.

- Version used: 
- Application (if applicable):

**Comment by AArnott** [comment]
Thanks for the report. I suspect we haven't any tests for operator overloads, so we can add that.

FWIW though, a thread affinitized operator overload sounds like it will breed confusion. Operators generally are expected to perform very quickly and without thread affinity.
