### ISSUE TITLE
VSTHRD100 fails to report async void event handlers

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#469]
#### Bug description

VSTHRD100 fails to report async void event handlers.

#### Repro steps

```csharp
button.Click += async (sender, e) => await Task.Delay(100);
```

#### Expected behavior

VSTHRD100 is reported, because an `async void` method is defined.

#### Actual behavior

VSTHRD100 is not reported.

- Version used: 15.8.132
- Application (if applicable): GitExtensions

**Comment by AArnott** [comment]
VSTHRD100 was coded up explicitly to allow async event handlers. 

https://github.com/Microsoft/vs-threading/blob/bd4273591de8836409bb58b490ef041f727adaf6/src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD100AsyncVoidMethodAnalyzer.cs#L70-L75

I think they're still evil and should be avoided. Event handlers that throw may crash the process whether they are async or not, but their completion cannot be tracked and thus could be incomplete when the app shuts down, so I think it's still an anti-pattern. So I could probably be persuaded that we should change the behavior of the analyzer. If we were concerned about the change, we could make it based on configuration perhaps (by introducing a stylecop.json-like file for vs-threading). But I hope we wouldn't need to worry about that and just change the behavior.
