### ISSUE TITLE
v16.0 threading package should depend on analyzer package

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-threading#483]
The v16.0 threading package regressed from 15.8 in that it no longer depends on the analyzer package so that that is automatically brought in.

**Comment by AArnott** [comment]
This regressed in a5297b513ef1f07869f3d23c24f9aba22fc9dd26

**Comment by AArnott** [comment]
This was fixed in 16.4.

**Comment by DaRosenberg** [comment]
IMO the fix is a regression, and the regression was a fix. See #605 for an explanation.
