### ISSUE TITLE
What's the default severity of each rules?

### ISSUE THREAD

**Issue by iron9light** [microsoft/vs-threading#498]
Where can I find this info?

**Comment by AArnott** [comment]
The analyzer rules are documented [here](https://github.com/microsoft/vs-threading/blob/master/doc/analyzers/index.md). 

What do you mean by "default action"? Are you talking about their code fixes?

**Comment by iron9light** [comment]
No, I mean actions like: Error, Warning, None, Suggestion etc.
https://github.com/dotnet/roslyn-analyzers/wiki#severity-levels-for-analyzers

**Comment by AArnott** [comment]
Ah, default severity levels then. I agree that would be good to document. But I'm curious why not install the package and customize the severity if necessary? How does knowing their severity in advance help you?

**Comment by iron9light** [comment]
I think most one, like me, just add the Analyzer and see if there's any error to fix.
They can fix the issues or disable some rules.
But if some rules are disabled by default, e.g. VSTHRD111, they don't even be aware of this rule.
Maybe they will enable it if know that the rule is disabled by default.

**Comment by AArnott** [comment]
Thanks for the insight into what you're doing. I'll keep this issue active to track documenting the default severity.

**Comment by AArnott** [comment]
Closed by 3304714fc983bdde524a2b7ff0b1dd051d63bb06
