### ISSUE TITLE
Tests hang on .NET Core

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-threading#499]
The tests hang on .NET Core 2.1. 

Re-enable testing in testfx.yml and investigate and fix hangs.

**Comment by AArnott** [comment]
`StaFact` isn't running at all either (not discovered on linux).

**Comment by sharwell** [comment]
@AArnott should this be closed?

**Comment by AArnott** [comment]
Yes, it seems we have nearly all tests running regularly on .NET Core now.
