### ISSUE TITLE
AsyncSemaphore can let too many callers enter when requests are cancelled

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-threading#521]
#### Bug description

Thread 1 is canceled while waiting to enter the semaphore, but so soon after it asks for the semaphore that the waitTask is completed by the time we check it (before we yield). Thread 1 is now "in" the semaphore but isn't accounted as such. This immediately would let one more thread in concurrently. And when thread 1 exits the semaphore, it will release it, leading to the semaphore allowing 2 threads from then on.

This bug in AsyncSemaphore has been present since its original version (many years ago). But StreamJsonRpc 2.0 was the first version that was vulnerable to it (or at least, the first version that would catch it when it happened and throw an exception). Which could explain failures like this appearing in VS as early as 16.1. We'll get this fixed in vs-threading and patch 16.4 immediately, and 16.3 as soon as we can get it approved. The risk of the fix should be low. Although it is in a very low-level class used in many places, the effect of the change should be very constrained and exactly what we need.

#### Repro steps

Have a thread trying to enter the semaphore with a CancellationToken that another thread cancels at exactly the same time. The cancellation has to take effect at a very narrow race condition between when *we* check for cancellation and when the SemaphoreSlim.EnterAsync method checks.

#### Expected behavior

Cancellation should be handled without allowing the caller to think they entered the semaphore.

#### Actual behavior

The caller is told they have entered the semaphore. But they haven't, so another thread may be allowed in immediately as well. When the canceled request *exits* the semaphore, the release the semaphore that they never really entered. This leads to the semaphore's AvailableCount being incremented by one. In a semaphore created with an initialCount of 1, this means that it will become a semaphore with 2 slots. From then on, too many will be allowed in.

- Version used: 16.3. But this bug impacts all previous versions.

**Comment by CyrusNajmabadi** [comment]
I am hitting this non-stop.  Can we get this in the next preview?

**Comment by AArnott** [comment]
Yes: it's already in Preview 2. And we're servicing 16.3 as well.

**Comment by CyrusNajmabadi** [comment]
@aarnott.  Great!  Any news on when that will release?  For example, will it be this week?  I was hoping to get a bunch of work done then, but this is totally blocking things :(

**Comment by AArnott** [comment]
I don't know when either will be released. 

Given you're in a pinch and it's impacting you severely, here's a workaround: you can patch it manually: 
Download the v16.3.59 package [from NuGet](https://www.nuget.org/packages/microsoft.visualstudio.threading) and copy the `lib\net472\Microsoft.VisualStudio.Threading.dll` file to 
`Common7\ide\PublicAssemblies\Microsoft.VisualStudio.Threading.16.0`

The v16.3.59 package isn't on nuget.org yet, but I'll get it there in a few minutes.

**Comment by CyrusNajmabadi** [comment]
oh thank you! :)
