### ISSUE TITLE
VSTHRD103 should allow calling Task.Result after awaiting Task.WhenAll

### ISSUE THREAD

**Issue by RehanSaeed** [microsoft/vs-threading#541]
#### Bug description

The following code produces a false positive for VSTHRD103.

```c#
Task<string> task1 = someMethod();
Task<string> task2 = someMethod();

await Task.WhenAll(task1, task2);

var result1 = task1.Result;
var result2 = task2.Result;
```

#### Expected behavior

It should be allowed to call `.Result` in this case.

#### Actual behavior

VSTHRD103 is raised.

- Version used: 16.4.16

**Comment by AArnott** [comment]
There are a variety of special cases where we can infer that a task has completed and thus calling `Result` would be safe. This is just one of them. Supporting all of them would be difficult. We do special case some of them, and this seems like a reasonable one, but IIRC we don't even support allowing `await task; return task.Result`, which would be even more obvious and probably more common that your case here.

To help prioritize this, what would prevent you from using `var result1 = await task1;` here?

**Comment by RehanSaeed** [comment]
I could in my particular case. However, I also work on the Cortana UWP app and adding four extra `await`'s adds 10-20KB to the app size which is to be avoided. It also hits performance a little.

**Comment by AArnott** [comment]
really? I wonder why awaits are so costly in size for UWP. It certainly isn't as costly for ordinary .NET Framework apps.
Anyway, good to know. I wouldn't worry about performance since you already have one await in your async method. The first await (or simply adding the async modifier to the method signature) is costly in terms of size and a little of perf I realize, but I expect adding another await on a completed Task should have very minimal cost.

**Comment by RehanSaeed** [comment]
`await` gets translated into a whole state machine worth of code when compiled. Then UWP uses .NET Native to compile the C# app to C++, this seems to amplify the app size increase.

Not sure about the performance that you mention. Would have to benchmark that to make sure.

**Comment by AArnott** [comment]
await itself is only translated into a goto statement with a few statements in each branch to return or obtain the result of the Task. It's minimal. It effectively adds 1 state to an existing state machine that the `async` modifier on the method created.
Are you sure this 10-20KB app size cost comes from *adding* awaits to an already async method that already includes 1 await? It sounds like you might be conflating the cost of an async method with the cost of adding another await.

**Comment by RehanSaeed** [comment]
Ah yes, you are indeed correct. It's the other way around.

**Comment by AArnott** [comment]
Great. So, how important would enhancing the analyzer be? Is replacing `.Result` with `await` a cheap solution for you after all?

**Comment by RehanSaeed** [comment]
Yes, I guess so.

**Comment by zmarty** [comment]
We use await Task.WhenAll(...), then .Result prettyu much everywhere in an internal Microsoft project. It would be nice to fix this, even as a special case.

**Comment by AArnott** [comment]
@zmarty: can you provide some sample code so we can evaluate whether a simple fix to the analyzer would suffice? For example, are the calls to `Task.Result` always following in the same method where the `await Task.WhenAll` took place?

**Comment by zmarty** [comment]
This is straight from our code, and includes the workaround we want to avoid:

```csharp
            await Task.WhenAll(
                playerNameTranslationsTask,
                freeAgentNameTranslationsTask,
                playerSatoriIdTask,
                playerOldMSNIdTask,
                playerOneServiceIdTask,
                playerPrecomputedAttributesTask);

            var playerNameTranslations = await playerNameTranslationsTask;
            var freeAgentNameTranslations = await freeAgentNameTranslationsTask;
            var playerSatoriId = await playerSatoriIdTask;
            var playerOldMSNId = await playerOldMSNIdTask;
            var playerOneServiceId = await playerOneServiceIdTask;
            var playerPrecomputedAttributes = await playerPrecomputedAttributesTask;
```

**Comment by AArnott** [comment]
Thanks. That does look pretty straightforward. Why is it important to you to use `playerNameTranslationsTask.Result` syntax instead? If any of those tasks failed, `Task.Result` would throw `AggregateException` instead of the original exception, whereas the `await` syntax will re-throw the original exception type.

**Comment by DRAirey1** [comment]
I have the same issue.  Want to use WhenAll for it's compact form.  While I agree the two forms in zmarty's example are equivalent, the API gives us the option to choose which form.  If there's a problem with the API, then let's log the problems on the API project.  This appears to me, as I understand the **WhenAll** method and the **Result** property, to be a problem with the analyzer, not the API.

**Comment by bbrandt** [comment]
@zmarty Why would `Task.WhenAll()` even be necessary here?

> ```cs
>             var playerNameTranslationsTask = GetPlayerNameTranslationsAsync();
>             var freeAgentNameTranslationsTask = GetFreeAgentNameTranslationsAsync();
>             //...
>             var playerPrecomputedAttributesTask = GetPlayerPrecomputedAttributesAsync();
>
>             await Task.WhenAll(
>                 playerNameTranslationsTask,
>                 freeAgentNameTranslationsTask,
>                 playerSatoriIdTask,
>                 playerOldMSNIdTask,
>                 playerOneServiceIdTask,
>                 playerPrecomputedAttributesTask);
> 
>             var playerNameTranslations = await playerNameTranslationsTask;
>             var freeAgentNameTranslations = await freeAgentNameTranslationsTask;
>             var playerSatoriId = await playerSatoriIdTask;
>             var playerOldMSNId = await playerOldMSNIdTask;
>             var playerOneServiceId = await playerOneServiceIdTask;
>             var playerPrecomputedAttributes = await playerPrecomputedAttributesTask;
> ```

  Wouldn't you instead do:
```cs
            var playerNameTranslationsTask = GetPlayerNameTranslationsAsync();
            var freeAgentNameTranslationsTask = GetFreeAgentNameTranslationsAsync();
            //...
            var playerPrecomputedAttributesTask = GetPlayerPrecomputedAttributesAsync();

            var playerNameTranslations = await playerNameTranslationsTask;
            var freeAgentNameTranslations = await freeAgentNameTranslationsTask;
            var playerSatoriId = await playerSatoriIdTask;
            var playerOldMSNId = await playerOldMSNIdTask;
            var playerOneServiceId = await playerOneServiceIdTask;
            var playerPrecomputedAttributes = await playerPrecomputedAttributesTask;
```

If you are independently starting each of these tasks and assigning to variables, like `playerNameTranslationsTask` and `freeAgentNameTranslationsTask`, they will still be running in parallel.  By the end of the last ` await playerPrecomputedAttributesTask` this would have the same effect and similar performance characteristics as `Task.WhenAll(...)`, right?  I could be missing some understanding of what  `Task.WhenAll(...)` does differently.

**Comment by AArnott** [comment]
@bbrandt good point. The only functional difference is that `await Task.WhenAll` will throw an `AggregateException` with _all_ failures at once, whereas the alternative would only throw the exception for the first failing task it encounters.
