### ISSUE TITLE
Analyzer/CodeFixProvider for async Queries

### ISSUE THREAD

**Issue by tanveerbadar** [microsoft/vs-threading#555]
Is there any analyzer for recommending async Linq-to-EF method usage from QueryableExtensions? I was unable to find one and if there are none, I am willing to take that up myself.

Example usage I have in mind would issue warning on code like this:

`dbSet.FirstOrDefault(filter)`

and offer to change this to:

`await dbSet.FirstOrDefaultAsync(filter)` instead, taking into account if the containing method itself is async or not.

**Comment by tanveerbadar** [comment]
VSTHRD103 already has the ability to warn for such cases where both variants of a method are present and the synchronous version is called.

**Comment by AArnott** [comment]
In your example, what type does `dbSet.FirstOrDefault(filter)` return? That doesn't *look* like an async method. Why would you await it?
And if it *does* return an awaitable type, analyzers already exist to point out that you should await the result.

**Comment by tanveerbadar** [comment]
My bad, I forgot to include the `Async` in the second snippet.

My feature request is to have an analyzer which can replace calls to `IQueryable<T>.FirstOrDefault()` (and like) with calls to `QueryableExtension` methods when a matching one exists, since the extension ones are asynchronous.

P.S.: Let me update the post to fix the typo.

**Comment by AArnott** [comment]
The VSTHRD103 analyzer should already do this. See the following test, which confirms it suggests that you await the async extension method alternative where one exists:

https://github.com/microsoft/vs-threading/blob/8ae9d4af7566106b472eac25fa7084ac4146f016/src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD103UseAsyncOptionAnalyzerTests.cs#L867-L911

**Comment by tanveerbadar** [comment]
I do not think this test case demonstrates the lack of an applicable analyzer. Your extension method type lies in the same namespace as the class containing the synchronous method. That is not the case with `System.Linq.IQueryable<T>` and `System.Data.Entity.QueryableExtensions`.

I will however give it a try over weekend and provide feedback.

**Comment by AArnott** [comment]
As with all extension methods, C# only recognizes them if you have a `using SomeNamespace;` at the top of your source file. When you try it out, make sure you have that, such that the extension method shows up as an option in your language service completion list. So long as you have that, the analyzer should suggest it.

**Comment by PaulVrugt** [comment]
I'm confused. We are using the `Microsoft.VisualStudio.Threading.Analyzers` version 17.8.14, but it doesn't recognize when I write an EF Core query, and use `ToArray()` or `First()` or anything instead of `ToArrayAsync()` and `FirstAsync()`, but this topic suggests it should.
