### ISSUE TITLE
Default analyser package to private asset

### ISSUE THREAD

**Issue by luhis** [microsoft/vs-threading#561]
#### Is your feature request related to a problem? Please describe.
When we use the Threading analyser, it is not added as a private asset, unlike stylecop.  This means that by default it is included in the built packages, then causing the analyser to run in projects importing my nuget

#### Describe the solution you'd like
Make the nuget package a private asset by default

#### Describe alternatives you've considered
I can set it to private asset manually, but i have to do it in many places

**Comment by AArnott** [comment]
Our first priority is for direct consumers of `Microsoft.VisualStudio.Threading` to also get the analyzers. There's unfortunately no way to do this without causing the analyzers to also propagate transitively to your own respective consumers.
Sorry.
