### ISSUE TITLE
inappropriate VSTHRD103 on EntityFrameworkCore's AddRange(Async) methods

### ISSUE THREAD

**Issue by springy76** [microsoft/vs-threading#584]
`DbContext` and `DbSet<TEntity>` both contain `AddRange`+`AddRangeAsync` pairs but the documentation on all overloads states that `AddRangeAsync` should rarely ever been used:

> This method is async only to allow special value generators, such as the one used by 'Microsoft.EntityFrameworkCore.Metadata.SqlServerValueGenerationStrategy.SequenceHiLo', to access the database asynchronously. For all other cases the non async method should be used. 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.addrangeasync?view=efcore-3.1

**Comment by AArnott** [comment]
Are these async methods marked as `[Obsolete]`? If so, then we have a bug in VSTHRD103 and can fix that. But if there is no way through API static analysis to know what the docs you quoted say, I'm afraid the best I can say is suppress the analyzer around your uses of EF.

**Comment by AArnott** [comment]
Closing due to no response.

**Comment by springy76** [comment]
Of course they are not obsolete. They are special methods for special seldom cases. And not to be used by everyone (means code changed to use them) just because this analyzer suggests so.

**Comment by AArnott** [comment]
Ok, that's a pretty bizarre API then to offer async methods that shouldn't be preferred over the sync ones. We don't have capacity to special case EF in our analyzer, so I suggest you simply suppress this particular analyzer in source files where you interact with these EF methods.

**Comment by nbarbettini** [comment]
@AArnott Sorry to bring this old thread back to life. I just ran into the same issue: `VSTHRD103` is raised on `DbSet<TEntity>.AddRange(params TEntity[])` but the EF Core documentation specifically says _not_ to use `AddRangeAsync` in user code. It is a bizarre special case, I agree.

I can suppress the analyzer in my source file, but it would be even nicer to add a global suppression for that EF Core method. I tried:

```
[assembly: SuppressMessage("Usage", "VSTHRD103:Call async methods when in an async method", Justification = "EF Core uses AddRange, not AddRangeAsync", Scope = "member", Target = "M:Microsoft.EntityFrameworkCore.DbSet`1.AddRange(`0[])")]
```

The above doesn't error but it also doesn't suppress the analyzer. I am not an expert in `Target` syntax - if you happen to spot the error, let me know!

**Comment by AArnott** [comment]
I'm no expert on global suppression syntax.
We should suppress the diagnostic when the async method variant is tagged as Obsolete. If AddRangeAsync is to be avoided, can/have they marked the method as obsolete?

**Comment by nbarbettini** [comment]
> They are not obsolete - just for very extended and seldom use cases, like framework extending extension-methods, or whatever.

Yeah, my understanding is that those methods should be considered internal, but are public because some generated code uses them. Weird situation for sure.

**Comment by Bouke** [comment]
Surely this analyser _could_ have a list of methods it doesn't raise this warning for. But you don't like having to special case this, as you expect that requests to special-case their methods will come pouring in. Regardless; both these libraries are provided by Microsoft. Please fix this amongst yourselves!

**Comment by ajcvickers** [comment]
See https://github.com/dotnet/roslyn-analyzers/pull/6858#issuecomment-1682739399

**Comment by AArnott** [comment]
Another option is for the EF to publish their own diagnostic suppression, as discussed here: https://github.com/microsoft/vs-threading/issues/1315#issuecomment-2243740973
