### ISSUE TITLE
!dumpasync fails because Microsoft.Diagnostics.Runtime.dll isn't nearby

### ISSUE THREAD

**Issue by genlu** [microsoft/vs-threading#590]
#### Bug description
!dumpasync command throws exception while debugging a dump in windbg

#### Repro steps
Open this dump in windbg (i'm using 1.2002.12002.0)
https://vsfeedback.azurewebsites.net/api/fileBlobMetrics/getAzureBlobFromTransferId?transferId=d71cd0fe5e994dc28e303d45b01d878e637033887675955757

#### Expected behavior
windbg shows stacks

#### Actual behavior
```
||2:2:150> !dumpasync
e0434352 Exception in C:\Users\gel\tools\SosThreadingTools.dll.dumpasync debugger extension.
      PC: 75e035d2  VA: 00000000  R/W: 80070002  Parameter: 00000000
```

- Version used: 
https://dev.azure.com/azure-public/vside/_build/results?buildId=8226&view=artifacts&type=publishedArtifacts
    deployables-Windows > win-x86

**Comment by piyush-saravagi** [comment]
Having the exact same issue.

**Comment by AArnott** [comment]
@genlu your feedback link doesn't work. Perhaps it was a time-expiring link. Can you send a link to the feedback ticket itself so I can get its attachment?

**Comment by genlu** [comment]
I think dumps from both tickets would trigger the crash:

https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1013058
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/978915

**Comment by piyush-saravagi** [comment]
@AArnott 
I would like to add that the issue persists even after using different dumps. 
I am using this https://we.tl/t-hgq6ow33i3
 
`
0:000> !dumpasync
`
`
e0434352 Exception in D:\Temp\SosThreadingTools_x64.dll.dumpasync debugger extension.`
`      PC: 00007ffc`15f69159  VA: 00000000`00000000  R/W: 80070002  Parameter: 00000000`00000000`

I am trying to get to the bottom of a deadlock and I am very keen to give !dumpasync a try. I think it could be super useful!

**Comment by AArnott** [comment]
@piyush-saravagi I have your dump and am taking a look. Because dumps can contain secrets, I recommend you take down your dump right now so others can't steal your secrets.

**Comment by AArnott** [comment]
@piyush-saravagi I can't operate on your dump because it is a 64-bit dump of a 32-bit process. This isn't something that the managed debugger in windbg can handle. Can you take a 32-bit dump of the hung process and try `!dumpasync` again?

To take a 32-bit dump, close all Task Manager windows. Then launch using `%windir%\syswow64\Taskmgr.exe` and take the dump from there. Taking the dump from procdump.exe or windbg should also work.

**Comment by AArnott** [comment]
Ok, so I've found the problem and why it always worked for me but not others. SosThreadingTools.dll has a dependency on `Microsoft.Diagnostics.Runtime.dll`, so you need that next to the first file or it won't work.

I'll keep this issue open to track documenting that and/or redistributing that second file with the first.

**Comment by piyush-saravagi** [comment]
Great! I'll give it a try. Thank you!

**Comment by AArnott** [comment]
In the meantime, you can get the dependency from https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime

**Comment by piyush-saravagi** [comment]
@AArnott I fetched Microsoft.Diagnostics.Runtime.dll from nuget and placed it right next to the SosThreadingTools_x64.dll
![image](https://user-images.githubusercontent.com/47992742/74671114-7e976d80-5178-11ea-8913-72442d245d30.png)

Ran `!dumpasync` again and this time it complained that Mscordacwks.dll is not loaded. Loaded it manually and got the same exception that we first saw. 

```
0:000> .load D:\Temp\dumpasync\SosThreadingTools_x64.dll
0:000> !dumpasync
Mscordacwks.dll not loaded into the debugger.
Run .cordll to load the dac before running this command.
0:000> .load C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscordacwks.dll
0:000> !dumpasync
e0434352 Exception in D:\Temp\dumpasync\SosThreadingTools_x64.dll.dumpasync debugger extension.
      PC: 00007ffe`ab159159  VA: 00000000`00000000  R/W: 80131509  Parameter: 00000000`00000000

```
Is there something else that I need to take care of? Thank you.

**Comment by AArnott** [comment]
@piyush-saravagi  Can you try building the SosThreadingTools project locally and loading the .dll from your output folder and tell me whether it works?
And if it doesn't work, attach VS with the managed debugger to the windbg engine host process so you can see what's failing.

**Comment by piyush-saravagi** [comment]
@AArnott I tried building the project locally and loading the .dll from the output folder but it still gave me the same exception. 
```
0:219> !dumpasync
e0434352 Exception in D:\Temp\vs-threading-16.5.132\vs-threading-16.5.132\bin\SosThreadingTools\Release\net472\win-x64\SosThreadingTools.dll.dumpasync debugger extension.
      PC: 00007ffe`ab159159  VA: 00000000`00000000  R/W: 93114510  Parameter: 00000000`00000000
```
Attached VS studio debugger to the windbg engine and it broke into Line 75 of DebuggerContext.cs
`runtime = dataTarget.ClrVersions.Single().CreateRuntime(module.FileName);`
because of this exception
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Mismatched dac. Version: 4.8.4121.0
  Source=Microsoft.Diagnostics.Runtime
  StackTrace:
   at Microsoft.Diagnostics.Runtime.DataTarget.CreateRuntime(ClrInfo clrInfo, String dacFilename, Boolean ignoreMismatch)
```

**Comment by AArnott** [comment]
Great. :)

I suspect the exception is because your mscordacwks is what is mismatched. However I don't know enough about the CLR to say exactly why that would be. Did you load sos or mscordacwks manually within that windbg session?

**Comment by scott-aptuity** [comment]
Having the same issue.  
Copied Microsoft.Diagnostics.Runtime.dll next to SosThreadingTool.dll
Ran:  
.load C:\Windows\Microsoft.NET\Framework64\v4.0.30319\sos.dll
.load C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscordacwks.dll

0:134> !dumpasync

e0434352 Exception in c:\tools\SosThreadingTools.dll.dumpasync debugger extension.
      PC: 00007ffb`a7084c48  VA: 00000000`00000000  R/W: 80070002  Parameter: 00000000`00000000

Everything should be x64 (windbg, mscordacwks, Sos, SosThreadingTool)

**Comment by sharwell** [comment]
We also have the option of taking the PerfView approach if distribution becomes annoying (embed dependencies as resources and use a custom loader that can extract them).

**Comment by AArnott** [comment]
Perhaps, if windbg will allow it.

As it is, the next github release will include a sosthreadingtools.zip file that contains all the dependencies, so I don't *think* it'll be a problem any more.
