### ISSUE TITLE
Do not use `WithMessage()` on tests

### ISSUE THREAD

**Issue by Evangelink** [microsoft/vs-threading#608]
#### Bug description
Some of the tests are using the `WithMessage()` check. This causes problems for non-US based machines as the message is translated so causing failed tests.

#### Repro steps

```csharp
/// <summary>
/// Verifies that no analyzer throws due to a missing interface member.
/// </summary>
[Fact]
public async Task MissingInterfaceImplementationMember()
{
	var test = @"
public interface A {
    void Foo();
}

public class Parent : A {
    // This class intentionally does not implement the interface
}

internal class Child : Parent {
    public Child() { }
}
";

	var expected = Verify.CompilerError("CS0535").WithLocation(6, 23).WithMessage("'Parent' does not implement interface member 'A.Foo()'");
	await Verify.VerifyAnalyzerAsync(test, expected);
}
```

#### Expected behavior

Test doesn't fail.

#### Actual behavior

Current test is broken because the message is different (in French in my context).

**Comment by weltkante** [comment]
Would it be possible to set the CurrentCulture in the test to force english texts?

**Comment by Evangelink** [comment]
It is possible but it was decided to not check messages for `CS` and to only check `WithArguments` for other rules in roslyn-analyzers so it might be better to do the same here. Besides, a new build (in spanish) was added.
