### ISSUE TITLE
VSTHRD114 handles anonymous delegates incorrectly

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-threading#618]
#### Bug description

The VSTHRD114 analyzer doesn't consider anonymous delegates. This creates both false positives and false negatives.

#### Repro steps

See tests added in https://github.com/microsoft/vs-threading/commit/94c7a6734101cb25c6e54fde1c09e73292ac7bdd (#619)

- Version used: 16.7.14.43703

**Comment by AArnott** [comment]
@Evangelink Would you be willing to fix this?

**Comment by Evangelink** [comment]
@AArnott Happy to help!

**Comment by AArnott** [comment]
Thanks!

**Comment by AArnott** [comment]
Please base your fix on the commit/PR I linked to above.
