### ISSUE TITLE
AsyncQueue does not cache Completion if already finished

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#62]
`AsyncQueue.Completion` has a fast path for the case where the result is cached. However, if the queue is already completed the first time this property is accessed, the backing field `AsyncQueue.completedSource` is never assigned. The fast path through this property could be improved by caching the `TplExtensions.CompletedTask` result so the lock doesn't need to be taken again.

**Comment by AArnott** [comment]
The field that stores the cached value is a TCS, rather than a Task. So we would need to add a field, making every instance larger. So unless you can suggest a real scenario where the lock is prohibitively expensive, this looks like a Won't Fix.

**Comment by sharwell** [comment]
👍
