### ISSUE TITLE
VSTHRD200 mis-fires on methods that return IAsyncEnumerable<T>-derived concrete types

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-threading#622]
The `AsyncPageable<T>` type implements `IAsyncEnumerable<T>`.
VSTHRD200 wants `IAsyncEnumerable<T>` returning methods to end in "Async" but does *not* want methods returning `AsyncPageable<T>` to end in Async.

![image](https://user-images.githubusercontent.com/3548/80821192-85d5f100-8b95-11ea-8255-c74b348a52fb.png)

VSTHRD200 should encourage all methods that return types that derive from `IAsyncEnumerable<T>` to end in Async.

**Comment by brandonh-msft** [comment]
Solved [here](https://github.com/microsoft/vs-threading/blob/cd072954b6132b2254aaf65fbf209012f654a168/src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs#L297)?

**Comment by AArnott** [comment]
I don't think the bug is fixed yet. The code you link to, @brandonh-msft, looks like it is expecting either of two precise types or any type that can be returned from a method with the `async` modifier, but `AsyncPageable` *may* not qualify that last condition (I'm not sure).

**Comment by brandonh-msft** [comment]
sweet!! What's the release process for this just so I know when I can expect to see these warnings/errors go away in our codebase?

It's tagged as Milestone 16.6 but as it just got fixed and we're already on 16.9 I'm thinking that's not quite accurate

**Comment by AArnott** [comment]
You can get this from our CI feed here: https://dev.azure.com/azure-public/vside/_packaging?_a=package&feed=vssdk&package=Microsoft.VisualStudio.Threading.Analyzers&protocolType=NuGet&version=16.10.50-alpha

Otherwise, it'll be on nuget.org with our first beta release for 16.10.
