### ISSUE TITLE
VSTHRD001 Shows code that does not compile

### ISSUE THREAD

**Issue by bitbonk** [microsoft/vs-threading#627]
#### Bug description
[VSTHRD001](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD001.md) Shows code that does not compile. In the current version of Microsoft.VisualStudio.Threading (16.6.13) [there is not such](https://www.fuget.org/packages/Microsoft.VisualStudio.Threading) thing as `ThreadHelper`.

Visual Studio warns me about using WPF's  `Dispatcher.Invoke` and that I should await `JoinableTaskFactory.SwitchToMainThreadAsync` instead. But it is not clear how to obtain an instance of `JoinableTaskFactory` so I can call and await `SwitchToMainThreadAsync`.  It looks like it was previously done using `ThreadHelper` but now not anymore. How do I do it now?

#### Repro steps
Use `Dispatcher.Invoke` in an async context. And see the  VSTHRD001 warning. Then google for it and find this: https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD001.md. The try to apply the suggestion from there.

#### Expected behavior
A clear explanaition given what to do. One that also compiles.

**Comment by AArnott** [comment]
Fair point, @bitbonk. Thanks for the feedback.

The code compiles within code that references the Visual Studio SDK. I'll add a note to that effect in the doc and add a tip in the doc that for code that runs in other applications to look up how that application exposes a `JoinableTaskFactory` instance for you use.

**Comment by bitbonk** [comment]
So in my plain WPF Application where I got the warning because I used `Dispatcher.Invoke`, I would create an instance of `JoinableTaskFactory` while I am still on the WPF main thread and then use that instance later to call `SwitchToMainThreadAsync ` instead of `Dispatcher.Invoke`?

**Comment by AArnott** [comment]
Yes. This is an area that we could probably document better. You should create your own JoinableTaskContext at the beginning of your application, and store it for use later.
