### ISSUE TITLE
Question: How do I use JoinableTaskFactory when I have multiple UI threads

### ISSUE THREAD

**Issue by bitbonk** [microsoft/vs-threading#628]
I'm writing a WPF controls library. The controls sometimes need to do asynchronous work and therefore sometimes need to switch back to the UI thread the controls where created on.  Previously I have been using [Dispatcher.Invoke](https://docs.microsoft.com/en-us/dotnet/api/system.windows.threading.dispatcher.invoke?view=netcore-3.1) to do this. 

Because I reference a[ nuget packge](https://www.nuget.org/packages/Nerdbank.Streams/2.2.26) that references _Microsoft.VisualStudio.Threading_, its analyzers have been forced upon me and I now beeing shamed for using `this.Dispatcher.Invoke`:

![image](https://user-images.githubusercontent.com/418030/81380735-a826bc00-910b-11ea-8644-dc64059e079b.png)

[So I went down the rabbit hole](https://github.com/microsoft/vs-threading/issues/627) understanding _Microsoft.VisualStudio.Threading_. It is clear to me how to use `JoinableTaskFactory` if an application just has one main thread. But in WPF it is perfectly fine that an appication has many UI threads and my control library must respect that.

How can I have one  `JoinableTaskFactory` singleton per UI thread that can be used by all my controls?
Or maybe having multiple UI threads is not what _Microsoft.VisualStudio.Threading_ was designed for?

**Comment by weltkante** [comment]
I don't have experience with this, but considering that `JoinableTaskContext` is bound to a specific UI thread and has its own `JoinableTaskFactory` I'd suspect you need multiple instances, which is probably bad and can lead to deadlocks if you jump between these UI threads.

Certainly an interesting question, I also have some applications with multiple UI threads, didn't make use of JTF there though, so I didn't run into this problem yet.

**Comment by AArnott** [comment]
> Because I reference a nuget packge that references Microsoft.VisualStudio.Threading, its analyzers have been forced upon me and I now beeing shamed for using this.Dispatcher.Invoke:

They're brought in by default, perhaps, based on another package you're referencing. But just FYI it isn't *forced*. You can turn off the analyzer package entirely or reduce the severity of some/all of its rules. That said, the rules _are_ useful for most applications so do consider adapting to them.

But great question about multiple UI threads. Yes, you would assign one instance of `JoinableTaskContext` to each main thread. Then you would use a JTF that comes from that context based on which main thread you're interacting with.

**But** don't create those. Per [this doc on libraries](https://github.com/microsoft/vs-threading/blob/master/doc/library_with_jtf.md) (which a control library would be), you should _not_ create your own instances of these types. Only _apps_ should create them, and expose them to the libraries that run in the process.

You're the first one to ask about using it in _controls_. My first thought is you shouldn't rely on JTF. Particularly if your controls will be used in a variety of applications that probably don't have a JTF. Even if they did, controls get dropped onto a design surface at design-time and you won't have a JTF instance there either. 
Instead, I think you should probably continue to use Dispatcher.  **But** do avoid `Dispatcher.Invoke`, which blocks the calling thread while you wait for the UI thread to process your delegate. Use Dispatcher.InvokeAsync or other of the async options. If you do that, you might find the warnings go away anyway. But if they still show up, you can turn off that particular analyzer rule in your library if needed.

**Comment by weltkante** [comment]
Ah, missed the part where the question was about a library

> Yes, you would assign one instance of JoinableTaskContext to each main thread. 

... if you are the owner that UI thread (started it and are responsible for shutdown)

Would this work out if you are an _application_ with multiple UI threads? Or, given you have access to the appropriate JTF instances of each UI thread, would this be prone to deadlock once async code needs to jump between threads?

I didn't study the implementation details to answer this, but my guess would be, because JTC is the top level element, that multiple distinct JTC instances don't coordinate and you risk deadlock once one of the UI thread needs to wait in a JoinTask?

**Comment by AArnott** [comment]
> I didn't study the implementation details to answer this, but my guess would be, because JTC is the top level element, that multiple distinct JTC instances don't coordinate and you risk deadlock once one of the UI thread needs to wait in a JoinTask?

That's exactly right. We have _no_ coordination between JTC instances.
