### ISSUE TITLE
Unable to build VSIX after upgrading from 16.5.126 to 16.6.13

### ISSUE THREAD

**Issue by drewnoakes** [microsoft/vs-threading#631]
Upgrading vs-threading packages in the [.NET Project System](https://github.com/dotnet/project-system) from 16.5.126 to 16.6.13 results in the following build error:

```
CreatePkgDef : error : ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.VisualStudio.Tools.CreatePkgDef.ProcessAssembly(String fileName, Hive hive, PkgDefContext context, Boolean register, RegistrationMode mode)
   at Microsoft.VisualStudio.Tools.CreatePkgDef.DoCreatePkgDef(InputArguments inputArguments)
   at Microsoft.VisualStudio.Tools.CreatePkgDef.Main(String[] arguments)
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
Could not load file or assembly 'file:///C:\Users\drnoakes\.nuget\packages\microsoft.bcl.asyncinterfaces\1.0.0\ref\net461\Microsoft.Bcl.AsyncInterfaces.dll' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)

	Microsoft.VisualStudio.Editors	C:\Users\drnoakes\.nuget\packages\microsoft.vssdk.buildtools\16.7.2\tools\vssdk\Microsoft.VsSDK.targets	1152	
```

Should the `Microsoft.Bcl.AsyncInterfaces` reference set `PrivateAssets`?

https://github.com/microsoft/vs-threading/commit/ae4e34dc9c4298a748f7d973c219809940ed2c90#diff-c74d7d829c6d49672bba46cad00c3c46R43

**Comment by AArnott** [comment]
This is actually a bug in the VS SDK imported targets that were written assuming all reference assemblies were loadable as runtime assemblies, which is not the case once a project starts referencing `Microsoft.Bcl.AsyncInterfaces`.
@wade0016 Is there a feedback ticket or any other external bug tracking this?

**Comment by drewnoakes** [comment]
Another hit on this (in the same repo), with a workaround:

https://github.com/dotnet/project-system/pull/6228/files#diff-c83acd616c9cfac5e0e2a6e74ee292fb

**Comment by AArnott** [comment]
I suspect this is fixed by https://www.nuget.org/packages/Microsoft.VSSDK.BuildTools/16.7.2041.

**Comment by drewnoakes** [comment]
Confirmed: https://github.com/dotnet/project-system/pull/6252
