### ISSUE TITLE
VSTHRD103: Analyzer unable to detect synchronous wait call in asynchronous function that returns IAsyncEnumerable

### ISSUE THREAD

**Issue by t-bzhan** [microsoft/vs-threading#633]
#### Bug description
Analyzer rule VSTHRD002 is unable to detect synchronous wait call in in asynchronous function that returns IAsyncEnumerable.

#### Repro steps
Use below code snippet:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace vsthreadtest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            await foreach(var i in FooAsync())
            {
                Console.WriteLine(i);
            }
        }

        public static async IAsyncEnumerable<int> FooAsync()
        {
            await Task.Delay(TimeSpan.FromSeconds(5));
            foreach (int i in Enumerable.Range(1, 10))
            {
                Task.Delay(TimeSpan.FromSeconds(5)).Wait();
                yield return i;
            }
        }

        public static IEnumerable<int> Foo()
        {
            foreach (int i in Enumerable.Range(1, 10))
            {
                Task.Delay(TimeSpan.FromSeconds(5)).Wait();
                yield return i;
            }
        }
    }
}
```

#### Expected behavior
All the Task.Delay(TimeSpan.FromSeconds(5)).Wait() calls will be detected.

#### Actual behavior
Task.Delay(TimeSpan.FromSeconds(5)).Wait() in FooAsync is not detected by VSTHRD002.
![image](https://user-images.githubusercontent.com/61817681/83521160-6540e400-a511-11ea-94ca-f4e179429c18.png)
.

- Version used: "Microsoft.VisualStudio.Threading.Analyzers 16.6.13"
- Application (if applicable): 

#### Additional context
I only test the behavior of application targeted "netcoreapp3.1".

**Comment by AArnott** [comment]
VSTHRD002 only highlights synchronous blocks in non-async Type returning methods. VSTHRD103 is the analyzer that should flag this.
