### ISSUE TITLE
Analyzer proposal: Dont compare Task<T> return values to null

### ISSUE THREAD

**Issue by bjornhellander** [microsoft/vs-threading#638]
Consider a method such as this:
`Task<SomeClass> SomeMethodAsync() { … }`

The following code (unintentionally missing an await inside an async method) does not currently trigger any of the VS Threading analyzers (and no CSxxxx warnings either):
`if (someObject.SomeMethodAsync() != null) return;`
Same problem with `==` of course.

Would be nice if it did, to catch simple typos which can still cause a lot of headache.

An analyzer with this intention could probably be defined in a number of other ways as well and still have more or less the same effect. One alternative could be to suggest that return values of type `Task` or `Task<T>` should always either be awaited or assigned to a variable.

**Comment by AArnott** [comment]
I'm not sure what the bug is or your proposed fix. If the method returns `Task` what's wrong with checking whether the result was (non-)null?
If it returns `Task<T>` is the concern that you meant to check `T` against `null` instead of the `Task<T>` wrapper?

**Comment by bjornhellander** [comment]
Yeah, might hade been a bit quick there. Sorry.

The situation that I wanted to describe was normal async/await code where the developer missed the await keyword when calling the method. So yes, the intention was to compare the T to null.

Technically, there is of course nothing wrong in the code and comparing the returned Task with null might be the intendend behaviour, but I claim that this situation is suspicious, similarly to how your already treat returning a null Task in a non async method as suspicious in VSTHRD114.
It is unusual and might not be what the developer wanted and I think that getting a warning would be a good thing.

**Comment by bjornhellander** [comment]
Updated the titel to reflect the described scenario.

**Comment by bjornhellander** [comment]
On the other hand, this might just as well be considered an oversight in CS4014, since the Task is lost and therefore can not be awaited. I will file an issue in dotnet/roslyn as well and see what they think.

**Comment by bjornhellander** [comment]
Opened issue on the compiler: https://github.com/dotnet/roslyn/issues/45479

**Comment by AArnott** [comment]
Let's continue with that issue. I don't think this proposal will rise as high enough priority to deliver on in the foreseeable future. But thank you for the suggestion.
