### ISSUE TITLE
Release Notes for the Nuget Package links to the wrong location

### ISSUE THREAD

**Issue by gregpakes** [microsoft/vs-threading#643]
The release notes link included in the nuget package links to the wrong location.

https://www.nuget.org/packages/Microsoft.VisualStudio.Threading.Analyzers/16.5.132

**Comment by gregpakes** [comment]
https://github.com/microsoft/vs-threading/pull/644

**Comment by AArnott** [comment]
Thanks for catching, and the PR.

**Comment by AArnott** [comment]
Closed by dea8d097b53dc14fded3e6e1c24d86d347e82a74
