### ISSUE TITLE
Missing release notes for version 16.7.54

### ISSUE THREAD

**Issue by bddckr** [microsoft/vs-threading#645]
#### Bug description
According to [NuGet](https://www.nuget.org/packages/Microsoft.VisualStudio.Threading/16.7.54) there is a new version available (16.7.54) for a few days now. However, this repository's release section does not list any version since the previous one (16.6.13). This also means the link on the above linked NuGet page in the Release Notes section is [leading to nothing](https://github.com/microsoft/vs-threading/releases/tag/v16.7.54).

Thanks for the great library and all the hard work btw! ❤️

**Comment by AArnott** [comment]
Fixed. Thanks for pointing it out.
