### ISSUE TITLE
VSTHRD010 doesn't fire for Microsoft.VisualStudio.OLE.Interop.IServiceProvider

### ISSUE THREAD

**Issue by digeff** [Microsoft/vs-threading#65]
VSTHRD010 doesn't fire for:
```
        public void TestMethodDoesntFire()
        {
            dynamic shell = ServiceProvider.GlobalProvider.GetService(typeof(Microsoft.VisualStudio.Shell.Interop.IVsShell));
            shell.something();
        }
        public object TestMethodDoesntFire2()
        {
            return (new object()) as Microsoft.VisualStudio.OLE.Interop.IServiceProvider;
        }
```

Though it correctly fires for:
```
        public void TestMethodDoesFire()
        {
            dynamic shell = ServiceProvider.GlobalProvider.GetService(typeof(IVsShell)) as MyCustomShell;
            shell.something();
        }
        public object TestMethodDoesFire2()
        {
            return (new object()) as Microsoft.VisualStudio.Shell.Interop.IVsShell;
        }

```

As an image:
![image](https://cloud.githubusercontent.com/assets/14098140/22571996/1aa4cb7e-e957-11e6-94c5-ebd9e9a5c71a.png)

The same issue happens for:
Microsoft.DiagnosticsHub.VisualStudio.SDK.IVsDiagnosticsHubService
and:
as Microsoft.DiagnosticsHub.IRecentListService

**Comment by AArnott** [comment]
Your case of `GlobalProvider.GetService` will never work unless we special case it, or we do what @sharwell suggests in #53: detect class method invocations that happen to implement interfaces that we already fire on.
