### ISSUE TITLE
VSTHRD010MainThreadUsageAnalyzer threw an exception of type 'System.Exception'

### ISSUE THREAD

**Issue by vchirikov** [microsoft/vs-threading#667]
#### Bug description
Analyzer VSTHRD010MainThreadUsageAnalyzer threw an exception.

#### Expected behavior
No exceptions happened

#### Actual behavior
Exception
```
CSC : warning AD0001: Analyzer 'Microsoft.VisualStudio.Threading.Analyzers.VSTHRD010MainThreadUsageAnalyzer' threw an exception of type 'System.Exception' with message 'Analyzer failure while processing syntax at ▋▋▋▋▋▋▋▋\ImageHelper.cs(134,35): System.NullReferenceException Object reference not set to an instance of an object.. Syntax: Graphics.FromImage(bitmap)'. [▋▋▋▋▋]
```

- Version used:  16.7.54

**Comment by AArnott** [comment]
Thanks for your report, @vchirikov. The [analyzer in question](https://github.com/microsoft/vs-threading/blob/master/src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD010MainThreadUsageAnalyzer.cs) is fairly sizeable, and we already use nullable ref annotations to try to avoid bugs such as these. I'm not sure I can make progress on this without a repro or at least a callstack. 
If you're interested in pursuing this, but concerned about information disclosure of your source code, you could compile these analyzers yourself in Debug configuration and run them locally so you can catch the failure in the debugger and either point us to the problem or offer a fix yourself.

**Comment by vchirikov** [comment]
Yep, I will try to do this.

**Comment by vchirikov** [comment]
Can't reproduce.
