### ISSUE TITLE
VSTHRD200 should not trigger on test methods

### ISSUE THREAD

**Issue by NN---** [microsoft/vs-threading#670]
#### Is your feature request related to a problem? Please describe.

Asynchronous unit test methods don't need Async suffix.

```cs
public class ATests
{
  [Test]
  public async F() // VSTHRD200
  {
    A a = new A();
    Assert.True(await a.T);
  }
}
```

#### Describe the solution you'd like

Either detect this automatically or add some exclusion rule.
For instance class ends with `Tests`.

#### Describe alternatives you've considered

I do not want to disable it completely in the solution.
It is possible to suppress it in Unit Tests projects but this is not scalable.

**Comment by AArnott** [comment]
> It is possible to suppress it in Unit Tests projects but this is not scalable.

It is indeed suppressible. This can be done via the msbuild `NoWarn` property, a .ruleset file, an .editorconfig file, or `#pragma` to name several. Why isn't this scalable?

**Comment by NN---** [comment]
Found solution 

```
[*Tests/*]
Suppress 
```

**Comment by jmevel** [comment]
> Found solution
> 
> ```
> [*Tests/*]
> Suppress 
> ```

Wait... Could you give a full example of this "Suppress"?
Where do you even configure this? 

This looks interesting so I'd like to know more.
Thanks 🙏
