### ISSUE TITLE
VSTHRD010 analyzer affects build time exponentially with large source code files

### ISSUE THREAD

**Issue by oskar** [microsoft/vs-threading#701]
#### Bug description
Analyzer affects build time exponentially with large source code files

#### Repro steps
1. Create an empty .NET Core 3.1 console app (builds in `00:00:01.087`)
2. Add a large c# source code file with ~1000 LOC (builds in `00:00:01.140`)
3. Reference the analyzer package Microsoft.VisualStudio.Threading.Analyzers (builds in `00:00:05.777`)
4. Increase large source code file to ~2000 LOC (builds in `00:00:18.672`)
5. Double the size again to ~4000 LOC (builds in `00:01:27.775`)

#### Expected behavior
Build time is not affected noticably by adding the analyzer package and build time is not increased exponentially with large source code files.

#### Actual behavior
Build time increases exponentionally with large source code files. For projects with large source code files this analyzer has detrimental effects on build time.

#### Additional context
Version used: Microsoft.VisualStudio.Threading.Analyzers 16.7.56.

I also tried to split the large file (~4k LOC) into 4 smaller files of ~1000 LOC and that seems to have a significantly smaller effect on build time (`00:00:06.392`).

**Comment by oskar** [comment]
See this simple repro project: https://github.com/oskar/large-file

**Comment by davkean** [comment]
This may or may not be related to this internal bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1240024.

**Comment by AArnott** [comment]
Thanks for the tip, David. However I don't see *any* lock contention when I repro this with perfview. Instead, I see VSTHRD010 calling `GetSymbolInfo` which is apparently very expensive:


Name | Inc % | Inc
-- | -- | --
module Microsoft.CodeAnalysis.CSharp.il <<Microsoft.CodeAnalysis.CSharp.il!CSharpExtensions.GetSymbolInfo>> | 84.0 | 39,584
module microsoft.visualstudio.threading.analyzers.csharp <<microsoft.visualstudio.threading.analyzers.csharp!VSTHRD010MainThreadUsageAnalyzer.AddToCallerCalleeMap>> | 84.0 | 39,584
module Microsoft.VisualStudio.Threading.Analyzers <<Microsoft.VisualStudio.Threading.Analyzers!Microsoft.VisualStudio.Threading.Analyzers.Utils+<>c__DisplayClass0_0.<DebuggableWrapper>b__0(value class Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext)>> | 84.0 | 39,584

**Comment by AArnott** [comment]
@sharwell I don't suppose you have an `IOperation`-based implementation of VSTHRD010 up your sleeve, do you?
Is it reasonable for Roslyn to be *so* very slow in this `GetSymbolInfo` API?

**Comment by sharwell** [comment]
> This may or may not be related to this internal bug: AB#1240024

It is not related. I updated that bug to point out the underlying issue.

> Is it reasonable for Roslyn to be so very slow in this GetSymbolInfo API?

I can't speak to reasonable, but I will say it's very common.

**Comment by AArnott** [comment]
The fix for this is now available in 16.8.55.

**Comment by oskar** [comment]
Just verified with version 16.8.55 in my repro project and it works like a charm. Thanks! 👍
