### ISSUE TITLE
No release notes for release 16.8.51

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [microsoft/vs-threading#707]
The NuGet Gallery page for version 16.8.51 of Microsoft.VisualStudio.ThreadingAnalyzers links to https://github.com/microsoft/vs-threading/releases/tag/v16.8.51, which is a dead link.

The same issue was previously reported (https://github.com/microsoft/vs-threading/issues/699) and fixed for version 16.7.56 as well. Is the fix for this something that can be automated?

**Comment by AArnott** [comment]
Thanks. I've fixed it.

It is automation that does this. We could 'fix' it, but then releases can be created on github.com even when another part of the pipeline is botched. Also, I typically have to edit the automatically created release notes so it's created in a 'draft' in the automation and I publish it after editing. Sorry for the inconvenience.

**Comment by Bosch-Eli-Black** [comment]
Okay. No worries. Thanks for the fix 🙂
