### ISSUE TITLE
Bad link on https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD002.md

### ISSUE THREAD

**Issue by abelykh0** [microsoft/vs-threading#708]
#### Bug description
Go to https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD002.md
The link on the bottom is dead

#### Repro steps
Click on a link "Asynchronous and multithreaded programming within VS using the JoinableTaskFactory"

#### Expected behavior
Link should work

#### Actual behavior
403 Forbidden

- Version used: 
- Application (if applicable): 

#### Additional context
Also, why don't we let using Wait(int millisecondsTimeout) overload (timeout). It seems OK to me, unless I am missing something (probably something behind this link?)

**Comment by AArnott** [comment]
Thank you. I've fixed the link.

`Wait(int)` may avoid a permanent deadlock, but it still synchronously blocks the calling thread which can lead to UI delays, and it is still vulnerable to blocking the very work that it intends to wait for.
