### ISSUE TITLE
AsyncReaderWriterResourceLock tries to exhaust read locks to unblock write lock requests leads to deadlocks

### ISSUE THREAD

**Issue by lifengl** [microsoft/vs-threading#710]
Dead lock can be formed through this pattern:

 1, Task A gets a read lock
 2, Task B tries to get a write lock
 3, Task C starts, tries to get a read lock. This request is blocked due to the pending write lock request
 4, Task A waits Task C to finish for other reasons. Inside VS, the reason is often to join a common/shared computation

Now, the system runs into a dead lock state, B cannot get the write lock, because A is waiting C. Various team members run into this dead lock when using the product. It is a general pattern and happens in various different functions of the product, so hard to measure. (DevDiv-1090831)

**Comment by lifengl** [comment]
add a unit test in the dev/lifengl/writeLockRequestHang branch to reproduce this issue.

**Comment by AArnott** [comment]
This sounds like it could only be solved at the ARWL level by a similar Join mechanism to what JTF already has. That as you know is so small feat. Do you intend to implement that?

**Comment by lifengl** [comment]
I haven't sorted out a solution, and about to start a conversation on this issue with the unit test.

Generally, we have two directions, one is to do dependencies tracking similar to JTF. If we go that direction, I doubt we would want to do the similar thing like JTF again. Maybe we need build the ARWL tightly with JTF, and use JTF to track dependencies (which will make it quite different from the current design.)

It seems to be an expensive one, especially that we hit this type of dead locks in a fairly row rate. We do want to fix it, but on what cost.

Another one to consider changing the strategy to issue a write lock. In the end, i don't think blocking all read lock after a write lock is pending is an essential sematic we need keep. If the code wants a read lock to be pending after the write lock is done, it need use strong logic to make sure two tasks are running in the defined order. It should not depend on how it is implemented here. (For example, if more requests are appended later when a write lock is issued, I think the write lock will still take priority even it is requested after read lock requests.)  Blocking issuing further read locks is basically to ensure we have chance to issue a write lock, if we have constant incoming read lock requests.  After blocking issuing new read locks, we assume the system will finish all existing read locks within a time limitation (which we don't know), and the write lock will be issued.  Maybe we can change that, if existing read locks cannot finish within certain period of time, we can allow pending read requests to go, and increases the time limitation. With controlling how to issue new read locks, we will still ensure to wait long enough to allow write lock to be issued by blocking further read locks, but allow this special type of dead lock to be resolved (maybe with some delays?)

Although, i don't have detail idea what is the better pattern to issue read locks to optimize the output of the system.

**Comment by AArnott** [comment]
I would be concerned about revising the JTF dependency system. You've done that once or twice in the past successfully, but it does have risk. If it makes it more complicated or slower though, that potentially makes it worse.

Your second idea may have some merit. I'm not a big fan of 'timeouts' that change behavior but if this is a low frequency deadlock and the timeout can accommodate it, perhaps that's a reasonably low cost way to go.

**Comment by lifengl** [comment]
After thinking about this again, I start to feel that it is unlikely to find a solution for this by adding some timeout gate without knowing task dependencies. Even we assume that the chance that a top read lock has an external dependencies is very small (lets say p << 1). When we reach the time limitation, and there are some read lock not yet released, we release another set of read locks. While it reduces (or eliminate, if we let all pending read requests to go) the chance earlier locks are blocked, each of the newly issued read lock will increase the chance of a new dependency. It seems unlikely we have a good way to make sure the system runs towards the right direction without additional assumptions, and it is likely unpredictable...

That means maybe we do want some JTF dependency involvement, which is something I didn't like in the first place, because the readerWriterLock is no longer an independent data structure to JTF. (Well... we know when we mix them in the same product, we need deal with the complexity like CPS has to, but that is a different thing.)  Basically, now this dead lock cannot be resolved in a product using the lock alone without using JTF.

Consider the chance of running into this is low, I don't think we want to add more complexity to the JTF structure itself. The cost to maintain dependency graph is already high and increases chance of lock contentions in some usage scenarios. What I think is a mixed solution, to resolve this, code to require read lock need run inside a JTF task. A read lock request will capture the ambient JTF task along with a top request. The thing it need from JTF is that JTF need support is a new method
List<JoinableTask> GetDependentTasksFromCandidateList(List<JoinableTask> sourceTasks, List<JoinableTask> candidateTasks) 
it basically find all JTF tasks from a candidate set which is depended by any of tasks in the source set.

When read locks are blocked by pending write locks, it can periodically check (maybe driven by a timer) whether any new read lock requests are depended by any issued & unfinished requests, and let those requests to be issued.  That will require no data structure change inside JTF, and doesn't require much memory.

**Comment by AArnott** [comment]
> Basically, now this dead lock cannot be resolved in a product using the lock alone without using JTF.

Not strictly true, I think. JTF is an example of the technology required to solve the deadlock, but ARWL could do it on its own and solve its own problem. It doesn't _have_ to be intermingled with JTF itself.
Unless you also want to solve a problem of main thread vs. lock holder deadlocks, but that's not the scope of the original problem you described.

I'm in favor of avoiding any significant complexity or risk to JTF as part of fixing this. So I'm glad you're thinking of ways to minimize that.

**Comment by lifengl** [comment]
Yeah, I agree... I think JTF actually contains two parts: a way to describe dependencies between tasks in the system, and uses the dependencies to manage/control a shared resource, in which case, it happens to be the UI thread.  And the similar thing can be used to manage other resources, ARWL is one sample. One reason of this is that the basic task system lacks this information.  However, if we have multiple of those systems in one process, it can be lots of mess, because the dependencies between tasks can be quite similar and will be repeated.  

Go further, maybe the task dependencies can be abstracted out, and let different resource controlling system to use it, or maybe it can be a part of the task system itself. But of course, those structures are created to resolve real product problems, and since we can get the product to work in the real world, a simple and lower risk change is far more preferred, especially there is no foreseeable benefiting to users with a complex solution.

If you are OK with the mixed solution, I will move on then...

**Comment by AArnott** [comment]
>  the mixed solution

I'm not sure which of the ideas you mentioned are the 'mixed' solution. Is it that you refactor JTF's dependencies so that they are independently consumed by any resource manager, including JTF for the main thread and ARWL for locking?

Will deadlocks between someone with a lock who wants the main thread and someone with the main thread who wants a lock (still?) be resolvable?

**Comment by lifengl** [comment]
It is what I talked about earlier. ARWL uses dependency relationship between ambient JTF when read lock is required to compute potential dependencies to resolve this specific dead lock. No data structure change is needed in JTF structure. (So no new notification, when write lock is blocked by issued read locks & there are pending read lock requests, ARWL will check dependencies on time-outs. (The chance of this dead lock is so slim, extra data structure/notification costs more statistically than checking it in time out occasionally.)

The deadlock between JTF and ARWL is a different story & it is resolved in CPS side, so I don't think we need do anything here.
