### ISSUE TITLE
Unspecified ordering for dequeue operations in AsyncQueue is problematic

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#75]
Currently the order in which dequeuers are provided values from `AsyncQueue<T>` is unspecified. This can lead to strange behavior such as the following:

### Single-threaded reordering (same cancellation token)

1. Thread *A* calls `DequeueAsync` with `CancellationToken.None`
1. Thread *A* calls `DequeueAsync` with `CancellationToken.None`
1. Thread *A* calls `Enqueue(1)`
1. Thread *A* calls `Enqueue(2)`

In this scenario, the queue will actually behave like a stack (LIFO) instead of a queue (FIFO) with providing values to the dequeuers.

### Single-threaded reordering (different cancellation tokens)

1. Thread *A* calls `DequeueAsync` with `CancellationToken.None`
1. Thread *A* calls `DequeueAsync` with a different `CancellationToken`
1. Thread *A* calls `Enqueue(1)`
1. Thread *A* calls `Enqueue(2)`

In this scenario, the value provided to the dequeue operation is steps 1 and 2 could be in either order (unspecified).

### Fairness problems

1. Thread *A* calls `DequeueAsync` with a cancellation token
1. Thread *B* calls `DequeueAsync` with `CancellationToken.None`, and the handler for this synchronously calls `DequeueAsync` with `CancellationToken.None`

In this scenario, if the ordering of the `Dictionary` provides orders `CancellationToken.None` before the other cancellation token, the dequeuer added by thread *A* will **never** receive a value, because the `Enqueue` operation will always prefer to provide a value for a dequeuer with `CancellationToken.None` before looking to any other value.

**Comment by sharwell** [comment]
💭 The `MultipleDequeuers` test could probably be updated to more strictly check for reordering for the first case (same thread, same cancellation token).

**Comment by AArnott** [comment]
Well, I want to say in theory I agree with you. And for your first scenario I can repro the problem. But while the 2nd and 3rd scenario are also likely broken, tests suggest otherwise. So it will take longer for me to write ones that fail.

**Comment by sharwell** [comment]
@AArnott I'm guessing the second one can be reproduced by duplicating the `MultipleDequeuers` test, while making the following changes:

1. Like you did for reproducing the first issue, make sure the assertions verify that items are dequeued in FIFO order.
1. Potentially use a larger number of dequeuers (the test has 5; try 100 and see if the bug easily reproduces there and adjust as it makes sense).
1. Create all the dequeuers with unique cancellation tokens: `queue.DequeueAsync(new CancellationTokenSource().Token);`

**Comment by sharwell** [comment]
@AArnott I'm guessing the third one can be reproduced with a cleverly-constructed single-producer, two-consumer implementation:

1. Each consumer uses its own `CancellationTokenSource` for all dequeuers added by that consumer.
1. Before adding the first item to the queue, each consumer should call `DequeueAsync` twice in round-robin fashion.
1. The handler for each consumer synchronously adds a new dequeuer for the same consumer. In other words, there are always four pending dequeuers waiting, two for each of the two consumers.

The test should verify that after adding two items from the same thread (single producer), each consumer had the opportunity to handle one of them. The current implementation would consistently fail this by assigning all of the added items to one of the consumers. However there is no way to know *which* of the two consumers this will be, so be careful not to make assumptions about this particular aspect in the test.

**Comment by AArnott** [comment]
OK, I have a test for scenario 2 that fails. I'll work on 3 next.
Incidentally, I had an idea this morning on how to fix this in a way that simplifies the code and reduces memory pressure. :)

**Comment by AArnott** [comment]
I was able to repro number 3 without any synchronous continuations because if you already have two dequeuers per CancellationToken, and you enqueue two items, no more DequeueAsync will complete or matter anyway.
