### ISSUE TITLE
Analyzer proposal: Use Task.Delay instead of Thread.Sleep in an async method

### ISSUE THREAD

**Issue by nbarbettini** [microsoft/vs-threading#754]
Using `Thread.Sleep()` inside an `async` method is a bad idea. `await Task.Delay()` is a drop-in replacement. It would be great to have an analyzer rule (and an accompanying code fix) to catch accidental use of `Thread.Sleep`.

Back on the old AsyncUsageAnalyzers repo, there was this discussion: https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers/issues/2
And also a related PR: https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers/pull/50

Is vs-threading the right place for an analyzer like this?

**Comment by AArnott** [comment]
`Thread.Sleep` is almost always a bad idea. If it appeared in a sync method, the diagnostic might even appear suggesting the method be made async.
I like the idea, and traditionally this would be a great repo for it. However the .NET team is in the process of migrating analyzers of general interest from this repo to theirs. So we should reach out to them to gauge interest before starting work here.

**Comment by nbarbettini** [comment]
Makes sense. Does reaching out mean cross-posting to a different repo, or something else?

**Comment by AArnott** [comment]
Yes. But I can't remember which dotnet repo keeps the new analyzers.

**Comment by davkean** [comment]
They are filling them directly in the runtime repository, here's an example: https://github.com/dotnet/runtime/issues/67123. 

//cc @terrajobst

**Comment by snjjay** [comment]
Task. Sleep is a synchronous thread that puts the thread to sleep so it can't be used for anything else. Task, on the other hand. Delay is an asynchronous thread that can be used to perform other tasks while it waits. Refer to this https://kodlogs.net/1/task-delay-vs-thread-sleep

**Comment by AArnott** [comment]
@snjjay: I think instead of "Task. Sleep" you meant "Thread.Sleep". 
Task.Delay is not any thread at all. It's an OS kernel timer that sends a message that the runtime translates into a thread pool work item. 

It's not clear to me what point you were trying to make with your comment. I think everyone here understands the difference between the two methods.

**Comment by Mihirpatel2005** [comment]
It’s indeed a great and helpful piece of information. I am happy that you shared these terrific ideas with us. Please keep it up and thanks for sharing. Read:https://kodlogs.net/1/task-delay-vs-thread-sleep
