### ISSUE TITLE
VSTHRD110 does not trigger when using null-conditional member access

### ISSUE THREAD

**Issue by AlexVallat** [microsoft/vs-threading#772]
#### Bug description
If the async method is called using null-conditional member access, no warning (neither VSTHRD110 nor CS4014) is raised.

#### Repro steps
```c#
class Example
{
    void Foo(Example mayNotBeNull, Example? mayBeNull)
    {
        DoStuffAsync();
        mayNotBeNull.DoStuffAsync();
        mayBeNull?.DoStuffAsync();
    }
    async Task DoStuffAsync() { /* ... */ }
}
```

#### Expected behavior
VSTHRD110 raised on all three lines in `Foo` method

#### Actual behavior
VSTHRD110 raised on first two lines in `Foo` method only, not on `mayBeNull?.DoStuffAsync()`

- Version used: 16.8.55
- Application (if applicable): Visual Studio 16.8.5

**Comment by AArnott** [comment]
As a note when this is addressed: the fix is not simply to add an `await`. The existing syntax would have to properly handle the null case in order to avoid a NRE:

```cs
await (mayBeNull?.DoStuffAsync() ?? Task.CompletedTask);
```
