### ISSUE TITLE
Why not use a synchronous callback in AsyncLazy

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#78]
I'm wondering why [this use of `ContinueWith`](https://github.com/Microsoft/vs-threading/blob/14f77875ae3a04108f0bd94ee9a1124dcf4a3073/src/Microsoft.VisualStudio.Threading.Shared/AsyncLazy.cs#L166-L174) in `AsyncLazy<T>` doesn't specify `ExecuteSynchronously`. It seems like that would be safe and marginally more efficient.

**Comment by AArnott** [comment]
Probably true, at least if .NET isn't already inlining the continuation as it often does.
