### ISSUE TITLE
Question: what are nesting factories used for?

### ISSUE THREAD

**Issue by weltkante** [microsoft/vs-threading#814]
I'm currently studying the codebase to evaluate how useful a port of the deadlock resolution to async frameworks on different runtimes would be and am a bit confused on the purpose of `nestingFactories`.

From what I can tell they contain a set of `JoinableTaskFactory` of its ambient tasks. This is [calculated](https://github.com/microsoft/vs-threading/blob/d5d6130ddd5bffb762c1bf13bf78dc356b8993e4/src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs#L1019) whenever a `JoinableTask` is launched.

The publically visible call sites to code which consumes `nestingFactories` are `SynchronizationContext.Post` and `SwitchToMainThread`. The usage of `nestingFactories` seems to be that it [will post](https://github.com/microsoft/vs-threading/blob/e5907f1fa83efe71b4af387899d7551668315797/src/Microsoft.VisualStudio.Threading/JoinableTask.cs#L768) to any `UnderlyingSynchronizationContext` in the hierarchy of ambient tasks.

So whats the point of all this effort? It is optimized to not allocate in the common case of only having a single `JoinableTaskFactory`, so obviously there is some issue with having multiple TaskFactories it tries to solve? There are two scenarios I can think of that lead to having multiple factories:
- Creating multiple instances of `JoinableTaskFactory` for the same `JoinableTaskContext` (including `JoinableTaskCollection`)
- Creating multiple instances from distinct `JoinableTaskContext` (different UI threads?)

Since `UnderlyingSynchronizationContext` forwards to the `JoinableTaskContext` the first case does not really solve any issues does it? It just posts multiple times to the same SC, so it actually is an unnecessary performance overhead if anything, isn't it? I'd have expected the set of nesting `JoinableTaskContext` to be stored, not the set of nesting `JoinableTaskFactory`.

If the factories are for different UI threads then I'm wondering if this code is even correct in the first place, why would it post to every underlying thread when targeting a specific JoinableTask? Doesn't this basically mean code can run on arbitrary threads which happen to be in the chain launching a `JoinableTask`?

So, any idea what the nesting factories code is there for? Any scenario it actually helps with?

**Comment by AArnott** [comment]
FYI @sharwell actually *did* port this to Java several years ago. At least, I think he did, but now I can't find anything on [an Internet search](https://www.bing.com/search?q=java+joinabletaskfactory&cvid=0d0177b88c3a40689cfeb1d0957ab948&aqs=edge..69i57.5231j0j1&pglt=43&FORM=ANNAB1&PC=U531) to back that up.
