### ISSUE TITLE
Mark AsyncUsageAnalyzers NuGet package as obsolete

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [microsoft/vs-threading#827]
The [AsyncUsageAnalyzers](https://www.nuget.org/packages/AsyncUsageAnalyzers/1.0.0-alpha003) NuGet package is still getting a lot of downloads, even though it's been superseded by [Microsoft.VisualStudio.Threading.Analyzers](https://www.nuget.org/packages/Microsoft.VisualStudio.Threading.Analyzers/)

Can the AsyncUsageAnalyzers NuGet package please be formally marked as obsolete and a note added to its NuGet package page that directs users to download Microsoft.VisualStudio.Threading.Analyzers instead?

Thanks 🙂

**Comment by AArnott** [comment]
@sharwell, it looks like you're the owner of the package. The repo behind it has already been archived.

**Comment by sharwell** [comment]
I wasn't aware this is now possible.

![image](https://user-images.githubusercontent.com/1408396/117404879-96fbc100-aebf-11eb-8a56-9623fcd45b9c.png)

**Comment by Bosch-Eli-Black** [comment]
@sharwell Haha, ya, I just discovered it myself a few days prior 🙂

Thanks for the fix! 🎉
