### ISSUE TITLE
VSCode support and/or example configuration enabling/disabling analyzers

### ISSUE THREAD

**Issue by chamons** [microsoft/vs-threading#828]
#### Is your feature request related to a problem? Please describe.
I tried using vs-threading on my existing test project and ran into trouble configuring vs-threading.  In particular:

- I was unable to get anything beyond severity critical to show up in my build log
- I was unable to configure my editorconfig to disable a few errors that caused 1000+ errors in my project

I believe it was due to my use of VSCode, as others who are using VS for Windows did not see the same issues.

#### Describe the solution you'd like
Documentation that lists the editorconfig keys to enable/disable analyzers or an example project/configuration.

**Comment by AArnott** [comment]
We do [document the analyzer IDs](https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/index.md) we emit. And I agree, this sounds like something with either your VS Code configuration or perhaps a bug in Omnisharp. I don't know that there's anything more we can do from this repo. Perhaps file a bug against VS Code or Omnisharp?

**Comment by chamons** [comment]
I guess. 

You could extend my request as "write documentation to show how to add analyzer to your project and enable/disable specific items", something like https://github.com/dotnet/roslyn-analyzers#microsoftcodeanalysisnetanalyzers and https://patriksvikruha.com/dotnet-solution-roslyn-analyzers.

I feel like it's non-trivial to configure a project to use vs-threading today.

**Comment by AArnott** [comment]
It's pretty straightforward within VS, which is the scenarios my team prioritizes at present. The docs you're asking for sounds like generally useful and good documentation, and thus would best be somewhere central for any analyzer consumer to find rather than in this repo.
