### ISSUE TITLE
Incorrect implementation of AwaiterMetadata.Equals

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#84]
The implementation of [`AwaiterMetadata.Equals`](https://github.com/Microsoft/vs-threading/blob/14f77875ae3a04108f0bd94ee9a1124dcf4a3073/src/Microsoft.VisualStudio.Threading.Shared/AsyncReaderWriterLock%2BHangReportContributor.cs#L247-L250) is comparing objects of different types and expecting good results. This type is used as a key in a has set, it should be corrected.

**Comment by AArnott** [comment]
It looks like while we have tests that cover this `AwaiterMetadata` class, no hash collision typically occurs so the `Equals` method is not called. So I have a fix for it, but it isn't unit tested, and I'm having a hard time imagining what unit test could force the modulus of the hashes to collide. So I'll skip the test this time around. 😲
