### ISSUE TITLE
AsyncReaderWriterResourceLock constructor leaves helper unassigned

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#86]
One of the `AsyncReaderWriterResourceLock<TMoniker, TResource>` constructors appears to leave the `helper` field uninitialized:

https://github.com/Microsoft/vs-threading/blob/14f77875ae3a04108f0bd94ee9a1124dcf4a3073/src/Microsoft.VisualStudio.Threading.Shared/AsyncReaderWriterResourceLock.cs#L47-L50

**Comment by AArnott** [comment]
zoiks! I guess no one calls that constructor. But I thought we added it there for CPS in debug mode.

**Comment by lifengl** [comment]
no, I didn't see anywhere we used this API.


________________________________
