### ISSUE TITLE
Unstable test: SwitchToMainThreadShouldNotLeakJoinableTaskWhenGetResultRunsLater 

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-threading#88]
From [a build where this test failed](https://ci.appveyor.com/project/AArnott/vs-threading/build/15.1.11+R), here is the output of the test:

```
    SwitchToMainThreadShouldNotLeakJoinableTaskWhenGetResultRunsLater [FAIL]
      Assert.Null() Failure
      Expected: (null)
      Actual:   Object { }
      Stack Trace:
        src\Microsoft.VisualStudio.Threading.Tests.Shared\JoinableTaskTests.cs(3141,0): at Microsoft.VisualStudio.Threading.Tests.JoinableTaskTests.SwitchToMainThreadShouldNotLeakJoinableTaskWhenGetResultRunsLater()
```

Here is [the relevant source line](https://github.com/Microsoft/vs-threading/blob/1aa93a60a80f7c846ff456fef8b73732f7f10bca/src/Microsoft.VisualStudio.Threading.Tests.Shared/JoinableTaskTests.cs#L3141)

**Comment by AArnott** [comment]
This test failure seems to repro reliably when I add a for loop to execute it 50 times.

**Comment by AArnott** [comment]
I can't figure out why the object leaks. A `!gcroot` of the object returns this:

```
!gcroot -all 037d8144 
Thread 2f44:
    07fce840 080d6421 Microsoft.VisualStudio.Threading.Tests.JoinableTaskTests.SwitchToMainThreadShouldNotLeakJoinableTaskWhenGetResultRunsLater() [C:\git\threading\src\Microsoft.VisualStudio.Threading.Tests\JoinableTaskTests.cs @ 3199]
        ebp+10: 07fce898
            ->  037d8144 System.Object

    07fce840 080d6421 Microsoft.VisualStudio.Threading.Tests.JoinableTaskTests.SwitchToMainThreadShouldNotLeakJoinableTaskWhenGetResultRunsLater() [C:\git\threading\src\Microsoft.VisualStudio.Threading.Tests\JoinableTaskTests.cs @ 3199]
        ebp+5c: 07fce84c
            ->  037d8144 System.Object

HandleTable:
    0740111c (strong handle)
    -> 037d8144 System.Object

    07401130 (strong handle)
    -> 037d8144 System.Object

    07401134 (strong handle)
    -> 037d8144 System.Object

    074018bc (strong handle)
    -> 037d8144 System.Object

Found 6 roots.
```

**Comment by BertanAygun** [comment]
I am not sure but couple things I can think of are: (1) maybe the anonymous functions are leaking which would have captured "result" object (2) the code is optimized so result = null isn't performed since result is not used afterwards.

**Comment by AArnott** [comment]
Thanks for your suggestions, @BertanAygun. They made me re-consider one more thing that I missed earlier:
In the existing test, in fact there is a delegate that hasn't been freed yet. And while in my local modification of the test I had fixed that problem (by running the message pump multiple times), I forgot to clear the local variable in each of the retry loops, so that would explain why it shows up in a thread register above. I have a reliably passing test now. :)
