### ISSUE TITLE
VSTHRD110 mis-fires on null coalescing operator

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-threading#881]
#### Bug description

When an async method's result is returned with `??` operator, VSTHRD110 claims the result isn't returned or awaited.

#### Repro steps

```cs
        internal Task<T> GetClientAsync<T>(CancellationToken cancellationToken) where T : VssHttpClientBase
        {
            return _vssConnection?.GetClientAsync<T>(cancellationToken) ?? Task.FromResult<T>(null);
        }
```

#### Expected behavior
 
No warning.

#### Actual behavior

A warning.

**Comment by drewnoakes** [comment]
Duplicate of #880?

**Comment by AArnott** [comment]
The two issues are regarding distinct analyzers. I wouldn't know till fixing it whether there is common code behind each analyzer such that fixing one will implicitly fix the other.

**Comment by peterdrier** [comment]
`private Task ShakeTreeAsync() => Tree?.ShakeAsync() ?? Task.CompletedTask;`

A simple example causing a VSTHRD110 warning where it shouldn't.
