### ISSUE TITLE
I don't believe that VSTHRD003 should be applicable to extension methods, or should it?

### ISSUE THREAD

**Issue by fgimian** [microsoft/vs-threading#891]
#### Bug description

VSTHRD003 is raised for Task extension methods.

#### Repro steps

A common pattern is using a `TimeoutAfter` extension method such as the one found [here](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/Scenarios/Infrastructure/TaskExtensions.cs).

```c#
namespace System.Threading.Tasks
{
    public static class TaskExtensions
    {
        public static async Task<T> TimeoutAfter<T>(this Task<T> task, TimeSpan timeout)
        {
            using (var cts = new CancellationTokenSource())
            {
                var delayTask = Task.Delay(timeout, cts.Token);

                var resultTask = await Task.WhenAny(task, delayTask);
                if (resultTask == delayTask)
                {
                    // Operation cancelled
                    throw new OperationCanceledException();
                }
                else
                {
                    // Cancel the timer task so that it does not fire
                    cts.Cancel();
                }

                return await task;  // VSTHRD003 fired here
            }
        }
    }
}
```

#### Expected behavior

I would personally expect this warning not to be raised on extension methods.

#### Actual behavior

VSTHRD003 is raised for Task extensions.

- Version used: 16.10.56
- Application (if applicable): N/A

#### Additional context

Please feel free to correct me if I'm incorrect about this.  If you could please propose how one would work around this warning if it's valid, that would be greatly appreciated too.

Huge thanks
Fotis

**Comment by AArnott** [comment]
I'm afraid extension methods in general aren't special in any way that prevents them from being vulnerable to the same problems of other methods. Some special purpose methods such as the one you mention may be ok and in such cases suppressing the analyzer for that method is an appropriate mitigation.

**Comment by fgimian** [comment]
Thanks so much for the reply @AArnott 😄
