### ISSUE TITLE
Microsoft.VisualStudio.Threading.Analyzers.VisualBasic missing from 17x nuget package?

### ISSUE THREAD

**Issue by VisualMicro** [microsoft/vs-threading#892]
Hi,

We have both .cs and a .vb extensions for Visual Studio. The CS extension/project is reporting correctly where SwitchToMainThread is required. 

However, the VB project shows the following warnings/info messages in the output window.

The vb project "Microsoft.VisualStudio.Threading.Analyzers 17.0.32-alpha" installed.

We are using VS2022.

Sorry if this is the wrong place to post this. Please let me know if you need more information.

Thanks

`Warning	BC42376	An instance of analyzer Microsoft.VisualStudio.Threading.Analyzers.VisualBasicVSTHRD001UseSwitchToMainThreadAsyncAnalyzer cannot be created from C:\Users\.......\packages\Microsoft.VisualStudio.Threading.Analyzers.17.0.17-alpha\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll : Could not load file or assembly 'Microsoft.VisualStudio.Threading.Analyzers, Version=17.0.17.6245, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..	myProject	C:\Users\.......\Visual.Micro.Visual.Studio.Arduino2022\vbc	1	Active
Warning	BC42376	An instance of analyzer Microsoft.VisualStudio.Threading.Analyzers.VisualBasicVSTHRD004AwaitSwitchToMainThreadAsyncAnalyzer cannot be created from C:\Users\.......\packages\Microsoft.VisualStudio.Threading.Analyzers.17.0.17-alpha\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll : Could not load file or assembly 'Microsoft.VisualStudio.Threading.Analyzers, Version=17.0.17.6245, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..	myProject	C:\Users\.......\Visual.Micro.Visual.Studio.Arduino2022\vbc	1	Active
Warning	BC42376	An instance of analyzer Microsoft.VisualStudio.Threading.Analyzers.VisualBasicVSTHRD011UseAsyncLazyAnalyzer cannot be created from C:\Users\.......\packages\Microsoft.VisualStudio.Threading.Analyzers.17.0.17-alpha\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll : Could not load file or assembly 'Microsoft.VisualStudio.Threading.Analyzers, Version=17.0.17.6245, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..	myProject	C:\Users\.......\Visual.Micro.Visual.Studio.Arduino2022\vbc	1	Active
Warning	BC42376	An instance of analyzer Microsoft.VisualStudio.Threading.Analyzers.VisualBasicVSTHRD012SpecifyJtfWhereAllowed cannot be created from C:\Users\.......\packages\Microsoft.VisualStudio.Threading.Analyzers.17.0.17-alpha\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll : Could not load file or assembly 'Microsoft.VisualStudio.Threading.Analyzers, Version=17.0.17.6245, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..	myProject	C:\Users\.......\Visual.Micro.Visual.Studio.Arduino2022\vbc	1	Active
Warning	BC42376	An instance of analyzer Microsoft.VisualStudio.Threading.Analyzers.VisualBasicVSTHRD105AvoidImplicitTaskSchedulerCurrentAnalyzer cannot be created from C:\Users\.......\packages\Microsoft.VisualStudio.Threading.Analyzers.17.0.17-alpha\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll : Could not load file or assembly 'Microsoft.VisualStudio.Threading.Analyzers, Version=17.0.17.6245, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..	myProject	C:\Users\.......\Visual.Micro.Visual.Studio.Arduino2022\vbc	1	Active
Warning	BC42376	An instance of analyzer Microsoft.VisualStudio.Threading.Analyzers.VisualBasicVSTHRD108AssertThreadRequirementUnconditionally cannot be created from C:\Users\.......\packages\Microsoft.VisualStudio.Threading.Analyzers.17.0.17-alpha\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll : Could not load file or assembly 'Microsoft.VisualStudio.Threading.Analyzers, Version=17.0.17.6245, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..	myProject	C:\Users\.......\Visual.Micro.Visual.Studio.Arduino2022\vbc	1	Active
Warning	BC42376	An instance of analyzer Microsoft.VisualStudio.Threading.Analyzers.VisualBasicVSTHRD109AvoidAssertInAsyncMethodsAnalyzer cannot be created from C:\Users\.......\packages\Microsoft.VisualStudio.Threading.Analyzers.17.0.17-alpha\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll : Could not load file or assembly 'Microsoft.VisualStudio.Threading.Analyzers, Version=17.0.17.6245, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..	myProject	C:\Users\.......\Visual.Micro.Visual.Studio.Arduino2022\vbc	1	Active
Warning	BC42376	An instance of analyzer Microsoft.VisualStudio.Threading.Analyzers.VisualBasicVSTHRD112ImplementSystemIAsyncDisposableAnalyzer cannot be created from C:\Users\.......\packages\Microsoft.VisualStudio.Threading.Analyzers.17.0.17-alpha\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll : Could not load file or assembly 'Microsoft.VisualStudio.Threading.Analyzers, Version=17.0.17.6245, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..	myProject	C:\Users\.......\Visual.Micro.Visual.Studio.Arduino2022\vbc	1	Active
Warning	BC42376	An instance of analyzer Microsoft.VisualStudio.Threading.Analyzers.VisualBasicVSTHRD001UseSwitchToMainThreadAsyncAnalyzer cannot be created from C:\Users\.......\packages\Microsoft.VisualStudio.Threading.Analyzers.17.0.17-alpha\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll: Could not load file or assembly 'Microsoft.VisualStudio.Threading.Analyzers, Version=17.0.17.6245, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..	myProject		1	Active
Warning	BC42376	An instance of analyzer Microsoft.VisualStudio.Threading.Analyzers.VisualBasicVSTHRD004AwaitSwitchToMainThreadAsyncAnalyzer cannot be created from C:\Users\.......\packages\Microsoft.VisualStudio.Threading.Analyzers.17.0.17-alpha\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll: Could not load file or assembly 'Microsoft.VisualStudio.Threading.Analyzers, Version=17.0.17.6245, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..	myProject		1	Active
Warning	BC42376	An instance of analyzer Microsoft.VisualStudio.Threading.Analyzers.VisualBasicVSTHRD011UseAsyncLazyAnalyzer cannot be created from C:\Users\.......\packages\Microsoft.VisualStudio.Threading.Analyzers.17.0.17-alpha\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll: Could not load file or assembly 'Microsoft.VisualStudio.Threading.Analyzers, Version=17.0.17.6245, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..	myProject		1	Active
Warning	BC42376	An instance of analyzer Microsoft.VisualStudio.Threading.Analyzers.VisualBasicVSTHRD012SpecifyJtfWhereAllowed cannot be created from C:\Users\.......\packages\Microsoft.VisualStudio.Threading.Analyzers.17.0.17-alpha\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll: Could not load file or assembly 'Microsoft.VisualStudio.Threading.Analyzers, Version=17.0.17.6245, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..	myProject		1	Active
Warning	BC42376	An instance of analyzer Microsoft.VisualStudio.Threading.Analyzers.VisualBasicVSTHRD105AvoidImplicitTaskSchedulerCurrentAnalyzer cannot be created from C:\Users\.......\packages\Microsoft.VisualStudio.Threading.Analyzers.17.0.17-alpha\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll: Could not load file or assembly 'Microsoft.VisualStudio.Threading.Analyzers, Version=17.0.17.6245, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..	myProject		1	Active
Warning	BC42376	An instance of analyzer Microsoft.VisualStudio.Threading.Analyzers.VisualBasicVSTHRD108AssertThreadRequirementUnconditionally cannot be created from C:\Users\.......\packages\Microsoft.VisualStudio.Threading.Analyzers.17.0.17-alpha\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll: Could not load file or assembly 'Microsoft.VisualStudio.Threading.Analyzers, Version=17.0.17.6245, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..	myProject		1	Active
Warning	BC42376	An instance of analyzer Microsoft.VisualStudio.Threading.Analyzers.VisualBasicVSTHRD109AvoidAssertInAsyncMethodsAnalyzer cannot be created from C:\Users\.......\packages\Microsoft.VisualStudio.Threading.Analyzers.17.0.17-alpha\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll: Could not load file or assembly 'Microsoft.VisualStudio.Threading.Analyzers, Version=17.0.17.6245, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..	myProject		1	Active
Warning	BC42376	An instance of analyzer Microsoft.VisualStudio.Threading.Analyzers.VisualBasicVSTHRD112ImplementSystemIAsyncDisposableAnalyzer cannot be created from C:\Users\.......\packages\Microsoft.VisualStudio.Threading.Analyzers.17.0.17-alpha\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll: Could not load file or assembly 'Microsoft.VisualStudio.Threading.Analyzers, Version=17.0.17.6245, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..	myProject		1	Active
`

**Comment by AArnott** [comment]
I cannot repro the problem. Here is the test solution I built for it:

[Bug892.zip](https://github.com/microsoft/vs-threading/files/7001768/Bug892.zip)

I see vs-threading analyzers correctly running in both projects. Can you change it as necessary to repro the problem and share back?

**Comment by VisualMicro** [comment]
Thanks very much for looking so quickly. Your projects have allowed me to clear a lot of nuget references that we not needed. the new SDK system does it all! When I re-look at the warnings they are pointing to "Unknown" project. The solution does use a number of shared code projects to cater for different VS versions. I will do some testing over the comming week to see if I can add some code that should raise a warning. It's not clear if the warnings are bogus or not. leave it with me thanks.

**Comment by davkean** [comment]
Will close this out as you appear to have resolved your problem.
