### ISSUE TITLE
Race condition in AsyncBarrier.SignalAndWait

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#90]
Currently `SignalAndWait` [resets `remainingParticipants`](https://github.com/Microsoft/vs-threading/blob/1aa93a60a80f7c846ff456fef8b73732f7f10bca/src/Microsoft.VisualStudio.Threading.Shared/AsyncBarrier.cs#L59), suggesting that the `AsyncBarrier` can be used multiple times to let tasks proceed in groups of size `participantCount`. However, the reset of `participantCount` and `waiters` is not atomic, allowing for a race condition when the barrier is used in this manner. The semantics after the barrier lets the first group of tasks proceed could be implemented as any of the following mutually-exclusive options:

* The barrier is reset atomically, allowing reuse with groups of size `participantCount`
* After the group of tasks proceeds, subsequent calls to `SignalAndWait` throw an exception
* After the first group of tasks proceeds, subsequent calls to `SignalAndWait` return a completed future (i.e. proceed immediately)

**Comment by AArnott** [comment]
To best retain backward compatibility, I think we must go with allowing multiple groups through.
