### ISSUE TITLE
VSTHRD103 Suggests method calls itself when async method calls non-async method

### ISSUE THREAD

**Issue by javierdlg** [Microsoft/vs-threading#92]
The analyzer suggests changing the name of a method from its non-async version to its async version without realizing the async method is itself.

Example:
```csharp
public async task CallMainAsync(){
  // do stuff
  CallMain()
  // do stuff
}

public void CallMain(){
  // more stuff
}
```
Analyzer will recommend changing `CallMain()` into `CallMainAsync()` without realizing `CallMainAsync()` is itself and that `CallMain()` is not the non-async counterpart but instead a synchronous part of `CallMainAsync()`

**Comment by AArnott** [comment]
Thanks for reporting, @javierdlg. Can you name which rule is misfiring here?

**Comment by javierdlg** [comment]
The rule is VSTHRD103
