### ISSUE TITLE
Bridge to RX

### ISSUE THREAD

**Issue by azeno** [microsoft/vs-threading#923]
First of all, thanks for this project! It truly helps a lot to have clear guidelines. 

Recently I was wondering if there's a nice way to bridge to the RX world? Especially the `ObserveOn` and `SubscribeOn` operators? Is there an extension out there already? Or is there a good argument against it?

I'd like to write something like `observable.ObserveOn(joinableTaskFactory)`

Thanks and keep up the good work!

**Comment by AArnott** [comment]
I'm not super familiar with RX. They have their own task schedulers, but they aren't `TaskScheduler` based from the .NET BCL, are they? 
JoinableTaskFactory understands _async_ work, whereas `TaskScheduler` does not (they deal only with one sync segment of an async method at a time). I wonder what RX's schedulers are like. 
A `JoinableTaskFactory` can be partially represented by a `SynchronizationContext`, if that's helpful.

**Comment by azeno** [comment]
Thanks for the prompt answer. I guess I'll simply use the `SelectMany(Func<Task<T>> taskSelector)` operator for now, like

    observable.SelectMany(async _ =>
    {
        await joinableTaskFactory.SwitchToMainThreadAsync(); 
        DoWorkOnUIThread(_);
    }
