### ISSUE TITLE
VSTHRD010 doesn't warn in some cases with unit tests

### ISSUE THREAD

**Issue by javierdlg** [Microsoft/vs-threading#93]
In some cases the [VSTHRD010](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD010.md) warning doesn't show with some unit test that use `IVsHierarchyItem` with MSTest

**Comment by AArnott** [comment]
Thanks for the report, @javierdlg. It would be great if you could include an actual method (perhaps trimmed down) and call out the line that the analyzer misfires on.
