### ISSUE TITLE
VSTHRD103 -- Duplicate of CA1849?

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [microsoft/vs-threading#954]
Now that .NET 6 has been released, we have the new [CA1849: Call async methods when in an async method](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1849) warning, which looks like it does basically the same thing as VSTHRD103, yay! 🙂

Are there any plans to remove the VSTHRD103 warning, since it's now covered by CA1849, or would that negatively impact projects that haven't yet moved to .NET 6, since they won't have the CA1849 warning?

**Comment by AArnott** [comment]
You have it exactly right. For folks seeing double, we recommend they disable the VSTHRD103 warnings. We'll remove it once most folks are using the new SDK or .NET analyzer package such that CA1849 is an option for them.

**Comment by Bosch-Eli-Black** [comment]
Okay, thanks! 🙂
