### ISSUE TITLE
AsyncSemaphore failure to increment on disposal

### ISSUE THREAD

**Issue by avsteele** [microsoft/vs-threading#955]
#### Bug description

It looks to me like there is some race condition in `AsyncSemphore` in that I can sometimes cause it to be the case that the semaphore does not increment its count when leaving the function (and the `Releaser` is disposed).  The semaphore stays at 0 forever after this, and `EnterAsync` will then timeout/throw forevermore.

#### Repro steps

It is sometime difficult to reproduce as there is definitely some timing component.  In the code below I can sometimes get it to trigger by breaking on the EnterAsync line until the token times out. But I've gotten to to trigger other ways too, just not consistently.

```cs
// ...
private AsyncSemaphore mySemaphore = new (1);
// ...
private async Task WorkAsync()
{
    using var cts = new CancellationTokenSource(1500);
    using var _ = await mySemaphore.EnterAsync(cts.Token).ConfigureAwait(false);   
    // ...work
}
```

The semaphore is only accessed via EnterAsync. All releases happen via the `using` statement. So it is difficult to see how the semaphore could be perpetually in a `currentCount=0` state in the absence of a bug.  In my code, at most 2 threads will be trying to enter the semaphore at once.

I was wondering if it might be related to either of these issues?

https://github.com/microsoft/vs-threading/issues/521
https://github.com/microsoft/vs-threading/issues/592

Though it kind of sounds like the opposite of 521. I don't think its 592 because I am not disposing the semaphore, just the `Releaser` via my `using` statement

**Comment by AArnott** [comment]
Thanks for your report and repro snippet. There is one other case I've heard that may be hitting the same issue. I'll be surprised if there's a race here, but cancellation can add an uncommon element that we sometimes forget about, so I'll be happy to take a look.

**Comment by AArnott** [comment]
What version of Microsoft.VisualStudio.Threading are you using when you see this, BTW?

**Comment by AArnott** [comment]
I can't see how this would be possible with the latest version of the code. That's not to say there isn't a bug here, but if you could provide a unit test or console app that loops until it fails, with some report from you that it does (eventually) repro, that would be immensely helpful.

**Comment by avsteele** [comment]
Thanks for looking into this.  If i can get this to reproduce in a reasonably sized snippet consistently I will share it. I will close now and ask for reopen if I can provide more.
