### ISSUE TITLE
Does vs-threading support cross platform?

### ISSUE THREAD

**Issue by ForkBug** [microsoft/vs-threading#967]
Although this lib depends on a win32 registry package, I think it may support cross platform after a simple test project.
But I couldn't find any statement about cross platform in the document.

And this is a great library, do you have any plan to merge it into dotnet BCL?

**Comment by AArnott** [comment]
Yes, it runs cross-platform. Avoid the registry API off-Windows and you'll be fine.  We test it on mac/linux regularly.

No plans to merge it into the BCL at this time.

**Comment by ForkBug** [comment]
Thank you. 
It's a really useful lib and provide some classes that BCL missed
