### ISSUE TITLE
Missing documentation for async hang debugging

### ISSUE THREAD

**Issue by JoshVarty** [Microsoft/vs-threading#97]
I was reading through the [threading rules](https://github.com/Microsoft/vs-threading/blob/master/doc/threading_rules.md) and came across the section on debugging hangs in the JTF:

>In the meantime, the most useful technique for analyzing async hangs is to attach WinDBG to the process and dump out incomplete async methods' states. This can be tedious, but we have a script in this file that you can use to make it much easier: [Async hang debugging](https://github.com/Microsoft/vs-threading/blob/master/scenario/analyze_hangs.md)

Unfortunately the link appears to be broken. Is this page available? I couldn't find it with a quick search for `.md` files in this repo.

**Comment by weltkante** [comment]
Talking of broken links, the "cookbook.md" link in the first paragraph needs to be also updated, it appears the file is called "cookbook_vs.md"
