### ISSUE TITLE
Get list of queued items in AsyncQueue

### ISSUE THREAD

**Issue by n9** [microsoft/vs-threading#986]
#### Is your feature request related to a problem? Please describe.

I want to get an ordered list of queued items in AsyncQueue.

#### Describe the solution you'd like

I would be nice to have a method that would return the ordered list of queued items.

#### Describe alternatives you've considered

I have not found any public members that can be used to achieve that.

**Comment by AArnott** [comment]
Can you share your scenario that would need such an API? The primary use case for this class does not require this.

**Comment by AArnott** [comment]
Thanks. And would `Queue<T>` or `List<T>` make an adequate substitute for your use case?

**Comment by AArnott** [comment]
The work may not be trivial, given exposing the inner collection would introduce a thread-safety problem so we would likely need to copy the collection within a lock and then return it. I can't promise a timeline or whether we'll get to this feature request at this point.

**Comment by n9** [comment]
I have mocked a PR: https://github.com/microsoft/vs-threading/pull/987.
